export const MajorData = [{ "id": 1, "major": "Engineering" },
{ "id": 2, "major": "Business Development" },
{ "id": 3, "major": "Accounting" },
{ "id": 4, "major": "Legal" },
{ "id": 5, "major": "Marketing" },
{ "id": 6, "major": "Accounting" },
{ "id": 7, "major": "Accounting" },
{ "id": 8, "major": "Research and Development" },
{ "id": 9, "major": "Human Resources" },
{ "id": 10, "major": "Support" },
{ "id": 11, "major": "Services" },
{ "id": 12, "major": "Engineering" },
{ "id": 13, "major": "Marketing" },
{ "id": 14, "major": "Product Management" },
{ "id": 15, "major": "Support" },
{ "id": 16, "major": "Product Management" },
{ "id": 17, "major": "Engineering" },
{ "id": 18, "major": "Services" },
{ "id": 19, "major": "Business Development" },
{ "id": 20, "major": "Sales" },
{ "id": 21, "major": "Engineering" },
{ "id": 22, "major": "Accounting" },
{ "id": 23, "major": "Engineering" },
{ "id": 24, "major": "Training" },
{ "id": 25, "major": "Engineering" },
{ "id": 26, "major": "Support" },
{ "id": 27, "major": "Business Development" },
{ "id": 28, "major": "Product Management" },
{ "id": 29, "major": "Research and Development" },
{ "id": 30, "major": "Product Management" },
{ "id": 31, "major": "Training" },
{ "id": 32, "major": "Product Management" },
{ "id": 33, "major": "Support" },
{ "id": 34, "major": "Legal" },
{ "id": 35, "major": "Human Resources" },
{ "id": 36, "major": "Services" },
{ "id": 37, "major": "Training" },
{ "id": 38, "major": "Product Management" },
{ "id": 39, "major": "Product Management" },
{ "id": 40, "major": "Services" },
{ "id": 41, "major": "Engineering" },
{ "id": 42, "major": "Sales" },
{ "id": 43, "major": "Business Development" },
{ "id": 44, "major": "Accounting" },
{ "id": 45, "major": "Services" },
{ "id": 46, "major": "Sales" },
{ "id": 47, "major": "Marketing" },
{ "id": 48, "major": "Marketing" },
{ "id": 49, "major": "Sales" },
{ "id": 50, "major": "Legal" },
{ "id": 51, "major": "Support" },
{ "id": 52, "major": "Engineering" },
{ "id": 53, "major": "Accounting" },
{ "id": 54, "major": "Research and Development" },
{ "id": 55, "major": "Human Resources" },
{ "id": 56, "major": "Research and Development" },
{ "id": 57, "major": "Human Resources" },
{ "id": 58, "major": "Human Resources" },
{ "id": 59, "major": "Product Management" },
{ "id": 60, "major": "Support" },
{ "id": 61, "major": "Research and Development" },
{ "id": 62, "major": "Human Resources" },
{ "id": 63, "major": "Business Development" },
{ "id": 64, "major": "Sales" },
{ "id": 65, "major": "Marketing" },
{ "id": 66, "major": "Services" },
{ "id": 67, "major": "Human Resources" },
{ "id": 68, "major": "Marketing" },
{ "id": 69, "major": "Sales" },
{ "id": 70, "major": "Engineering" },
{ "id": 71, "major": "Support" },
{ "id": 72, "major": "Accounting" },
{ "id": 73, "major": "Business Development" },
{ "id": 74, "major": "Sales" },
{ "id": 75, "major": "Support" },
{ "id": 76, "major": "Accounting" },
{ "id": 77, "major": "Human Resources" },
{ "id": 78, "major": "Training" },
{ "id": 79, "major": "Marketing" },
{ "id": 80, "major": "Services" },
{ "id": 81, "major": "Business Development" },
{ "id": 82, "major": "Support" },
{ "id": 83, "major": "Sales" },
{ "id": 84, "major": "Research and Development" },
{ "id": 85, "major": "Sales" },
{ "id": 86, "major": "Accounting" },
{ "id": 87, "major": "Product Management" },
{ "id": 88, "major": "Business Development" },
{ "id": 89, "major": "Human Resources" },
{ "id": 90, "major": "Services" },
{ "id": 91, "major": "Sales" },
{ "id": 92, "major": "Engineering" },
{ "id": 93, "major": "Human Resources" },
{ "id": 94, "major": "Services" },
{ "id": 95, "major": "Human Resources" },
{ "id": 96, "major": "Training" },
{ "id": 97, "major": "Sales" },
{ "id": 98, "major": "Support" },
{ "id": 99, "major": "Human Resources" },
{ "id": 100, "major": "Sales" },
{ "id": 101, "major": "Support" },
{ "id": 102, "major": "Services" },
{ "id": 103, "major": "Services" },
{ "id": 104, "major": "Sales" },
{ "id": 105, "major": "Accounting" },
{ "id": 106, "major": "Legal" },
{ "id": 107, "major": "Sales" },
{ "id": 108, "major": "Support" },
{ "id": 109, "major": "Services" },
{ "id": 110, "major": "Support" },
{ "id": 111, "major": "Marketing" },
{ "id": 112, "major": "Legal" },
{ "id": 113, "major": "Training" },
{ "id": 114, "major": "Research and Development" },
{ "id": 115, "major": "Human Resources" },
{ "id": 116, "major": "Training" },
{ "id": 117, "major": "Training" },
{ "id": 118, "major": "Sales" },
{ "id": 119, "major": "Marketing" },
{ "id": 120, "major": "Business Development" },
{ "id": 121, "major": "Product Management" },
{ "id": 122, "major": "Sales" },
{ "id": 123, "major": "Research and Development" },
{ "id": 124, "major": "Product Management" },
{ "id": 125, "major": "Support" },
{ "id": 126, "major": "Training" },
{ "id": 127, "major": "Support" },
{ "id": 128, "major": "Services" },
{ "id": 129, "major": "Engineering" },
{ "id": 130, "major": "Support" },
{ "id": 131, "major": "Sales" },
{ "id": 132, "major": "Services" },
{ "id": 133, "major": "Human Resources" },
{ "id": 134, "major": "Accounting" },
{ "id": 135, "major": "Marketing" },
{ "id": 136, "major": "Business Development" },
{ "id": 137, "major": "Support" },
{ "id": 138, "major": "Marketing" },
{ "id": 139, "major": "Business Development" },
{ "id": 140, "major": "Legal" },
{ "id": 141, "major": "Research and Development" },
{ "id": 142, "major": "Training" },
{ "id": 143, "major": "Marketing" },
{ "id": 144, "major": "Sales" },
{ "id": 145, "major": "Sales" },
{ "id": 146, "major": "Training" },
{ "id": 147, "major": "Sales" },
{ "id": 148, "major": "Training" },
{ "id": 149, "major": "Engineering" },
{ "id": 150, "major": "Marketing" },
{ "id": 151, "major": "Services" },
{ "id": 152, "major": "Human Resources" },
{ "id": 153, "major": "Support" },
{ "id": 154, "major": "Accounting" },
{ "id": 155, "major": "Business Development" },
{ "id": 156, "major": "Human Resources" },
{ "id": 157, "major": "Training" },
{ "id": 158, "major": "Support" },
{ "id": 159, "major": "Accounting" },
{ "id": 160, "major": "Training" },
{ "id": 161, "major": "Legal" },
{ "id": 162, "major": "Services" },
{ "id": 163, "major": "Human Resources" },
{ "id": 164, "major": "Legal" },
{ "id": 165, "major": "Human Resources" },
{ "id": 166, "major": "Engineering" },
{ "id": 167, "major": "Research and Development" },
{ "id": 168, "major": "Business Development" },
{ "id": 169, "major": "Research and Development" },
{ "id": 170, "major": "Sales" },
{ "id": 171, "major": "Product Management" },
{ "id": 172, "major": "Accounting" },
{ "id": 173, "major": "Business Development" },
{ "id": 174, "major": "Support" },
{ "id": 175, "major": "Business Development" },
{ "id": 176, "major": "Accounting" },
{ "id": 177, "major": "Human Resources" },
{ "id": 178, "major": "Sales" },
{ "id": 179, "major": "Research and Development" },
{ "id": 180, "major": "Product Management" },
{ "id": 181, "major": "Training" },
{ "id": 182, "major": "Training" },
{ "id": 183, "major": "Legal" },
{ "id": 184, "major": "Legal" },
{ "id": 185, "major": "Legal" },
{ "id": 186, "major": "Product Management" },
{ "id": 187, "major": "Services" },
{ "id": 188, "major": "Services" },
{ "id": 189, "major": "Marketing" },
{ "id": 190, "major": "Support" },
{ "id": 191, "major": "Accounting" },
{ "id": 192, "major": "Product Management" },
{ "id": 193, "major": "Support" },
{ "id": 194, "major": "Services" },
{ "id": 195, "major": "Training" },
{ "id": 196, "major": "Legal" },
{ "id": 197, "major": "Marketing" },
{ "id": 198, "major": "Human Resources" },
{ "id": 199, "major": "Sales" },
{ "id": 200, "major": "Business Development" },
{ "id": 201, "major": "Sales" },
{ "id": 202, "major": "Product Management" },
{ "id": 203, "major": "Legal" },
{ "id": 204, "major": "Support" },
{ "id": 205, "major": "Research and Development" },
{ "id": 206, "major": "Services" },
{ "id": 207, "major": "Marketing" },
{ "id": 208, "major": "Legal" },
{ "id": 209, "major": "Sales" },
{ "id": 210, "major": "Product Management" },
{ "id": 211, "major": "Support" },
{ "id": 212, "major": "Human Resources" },
{ "id": 213, "major": "Sales" },
{ "id": 214, "major": "Sales" },
{ "id": 215, "major": "Accounting" },
{ "id": 216, "major": "Training" },
{ "id": 217, "major": "Business Development" },
{ "id": 218, "major": "Accounting" },
{ "id": 219, "major": "Marketing" },
{ "id": 220, "major": "Services" },
{ "id": 221, "major": "Support" },
{ "id": 222, "major": "Legal" },
{ "id": 223, "major": "Legal" },
{ "id": 224, "major": "Product Management" },
{ "id": 225, "major": "Product Management" },
{ "id": 226, "major": "Training" },
{ "id": 227, "major": "Business Development" },
{ "id": 228, "major": "Engineering" },
{ "id": 229, "major": "Accounting" },
{ "id": 230, "major": "Legal" },
{ "id": 231, "major": "Training" },
{ "id": 232, "major": "Engineering" },
{ "id": 233, "major": "Product Management" },
{ "id": 234, "major": "Legal" },
{ "id": 235, "major": "Marketing" },
{ "id": 236, "major": "Human Resources" },
{ "id": 237, "major": "Engineering" },
{ "id": 238, "major": "Marketing" },
{ "id": 239, "major": "Accounting" },
{ "id": 240, "major": "Support" },
{ "id": 241, "major": "Business Development" },
{ "id": 242, "major": "Human Resources" },
{ "id": 243, "major": "Research and Development" },
{ "id": 244, "major": "Services" },
{ "id": 245, "major": "Engineering" },
{ "id": 246, "major": "Human Resources" },
{ "id": 247, "major": "Training" },
{ "id": 248, "major": "Marketing" },
{ "id": 249, "major": "Training" },
{ "id": 250, "major": "Business Development" },
{ "id": 251, "major": "Research and Development" },
{ "id": 252, "major": "Business Development" },
{ "id": 253, "major": "Business Development" },
{ "id": 254, "major": "Product Management" },
{ "id": 255, "major": "Sales" },
{ "id": 256, "major": "Legal" },
{ "id": 257, "major": "Marketing" },
{ "id": 258, "major": "Sales" },
{ "id": 259, "major": "Human Resources" },
{ "id": 260, "major": "Engineering" },
{ "id": 261, "major": "Research and Development" },
{ "id": 262, "major": "Services" },
{ "id": 263, "major": "Sales" },
{ "id": 264, "major": "Product Management" },
{ "id": 265, "major": "Human Resources" },
{ "id": 266, "major": "Research and Development" },
{ "id": 267, "major": "Engineering" },
{ "id": 268, "major": "Sales" },
{ "id": 269, "major": "Human Resources" },
{ "id": 270, "major": "Product Management" },
{ "id": 271, "major": "Research and Development" },
{ "id": 272, "major": "Marketing" },
{ "id": 273, "major": "Human Resources" },
{ "id": 274, "major": "Research and Development" },
{ "id": 275, "major": "Human Resources" },
{ "id": 276, "major": "Training" },
{ "id": 277, "major": "Support" },
{ "id": 278, "major": "Business Development" },
{ "id": 279, "major": "Sales" },
{ "id": 280, "major": "Marketing" },
{ "id": 281, "major": "Product Management" },
{ "id": 282, "major": "Training" },
{ "id": 283, "major": "Accounting" },
{ "id": 284, "major": "Human Resources" },
{ "id": 285, "major": "Sales" },
{ "id": 286, "major": "Legal" },
{ "id": 287, "major": "Business Development" },
{ "id": 288, "major": "Accounting" },
{ "id": 289, "major": "Sales" },
{ "id": 290, "major": "Services" },
{ "id": 291, "major": "Human Resources" },
{ "id": 292, "major": "Legal" },
{ "id": 293, "major": "Legal" },
{ "id": 294, "major": "Business Development" },
{ "id": 295, "major": "Legal" },
{ "id": 296, "major": "Human Resources" },
{ "id": 297, "major": "Human Resources" },
{ "id": 298, "major": "Accounting" },
{ "id": 299, "major": "Legal" },
{ "id": 300, "major": "Training" },
{ "id": 301, "major": "Services" },
{ "id": 302, "major": "Training" },
{ "id": 303, "major": "Training" },
{ "id": 304, "major": "Support" },
{ "id": 305, "major": "Support" },
{ "id": 306, "major": "Research and Development" },
{ "id": 307, "major": "Human Resources" },
{ "id": 308, "major": "Legal" },
{ "id": 309, "major": "Legal" },
{ "id": 310, "major": "Product Management" },
{ "id": 311, "major": "Human Resources" },
{ "id": 312, "major": "Services" },
{ "id": 313, "major": "Engineering" },
{ "id": 314, "major": "Services" },
{ "id": 315, "major": "Marketing" },
{ "id": 316, "major": "Training" },
{ "id": 317, "major": "Engineering" },
{ "id": 318, "major": "Legal" },
{ "id": 319, "major": "Product Management" },
{ "id": 320, "major": "Legal" },
{ "id": 321, "major": "Services" },
{ "id": 322, "major": "Business Development" },
{ "id": 323, "major": "Engineering" },
{ "id": 324, "major": "Legal" },
{ "id": 325, "major": "Training" },
{ "id": 326, "major": "Training" },
{ "id": 327, "major": "Support" },
{ "id": 328, "major": "Accounting" },
{ "id": 329, "major": "Services" },
{ "id": 330, "major": "Human Resources" },
{ "id": 331, "major": "Support" },
{ "id": 332, "major": "Services" },
{ "id": 333, "major": "Training" },
{ "id": 334, "major": "Engineering" },
{ "id": 335, "major": "Marketing" },
{ "id": 336, "major": "Sales" },
{ "id": 337, "major": "Marketing" },
{ "id": 338, "major": "Research and Development" },
{ "id": 339, "major": "Sales" },
{ "id": 340, "major": "Support" },
{ "id": 341, "major": "Marketing" },
{ "id": 342, "major": "Legal" },
{ "id": 343, "major": "Services" },
{ "id": 344, "major": "Accounting" },
{ "id": 345, "major": "Training" },
{ "id": 346, "major": "Accounting" },
{ "id": 347, "major": "Support" },
{ "id": 348, "major": "Marketing" },
{ "id": 349, "major": "Human Resources" },
{ "id": 350, "major": "Human Resources" },
{ "id": 351, "major": "Engineering" },
{ "id": 352, "major": "Product Management" },
{ "id": 353, "major": "Marketing" },
{ "id": 354, "major": "Marketing" },
{ "id": 355, "major": "Training" },
{ "id": 356, "major": "Marketing" },
{ "id": 357, "major": "Product Management" },
{ "id": 358, "major": "Engineering" },
{ "id": 359, "major": "Marketing" },
{ "id": 360, "major": "Product Management" },
{ "id": 361, "major": "Services" },
{ "id": 362, "major": "Sales" },
{ "id": 363, "major": "Accounting" },
{ "id": 364, "major": "Services" },
{ "id": 365, "major": "Human Resources" },
{ "id": 366, "major": "Accounting" },
{ "id": 367, "major": "Accounting" },
{ "id": 368, "major": "Human Resources" },
{ "id": 369, "major": "Research and Development" },
{ "id": 370, "major": "Product Management" },
{ "id": 371, "major": "Legal" },
{ "id": 372, "major": "Legal" },
{ "id": 373, "major": "Research and Development" },
{ "id": 374, "major": "Accounting" },
{ "id": 375, "major": "Business Development" },
{ "id": 376, "major": "Training" },
{ "id": 377, "major": "Human Resources" },
{ "id": 378, "major": "Research and Development" },
{ "id": 379, "major": "Training" },
{ "id": 380, "major": "Accounting" },
{ "id": 381, "major": "Legal" },
{ "id": 382, "major": "Training" },
{ "id": 383, "major": "Business Development" },
{ "id": 384, "major": "Business Development" },
{ "id": 385, "major": "Engineering" },
{ "id": 386, "major": "Engineering" },
{ "id": 387, "major": "Legal" },
{ "id": 388, "major": "Business Development" },
{ "id": 389, "major": "Support" },
{ "id": 390, "major": "Business Development" },
{ "id": 391, "major": "Legal" },
{ "id": 392, "major": "Services" },
{ "id": 393, "major": "Training" },
{ "id": 394, "major": "Legal" },
{ "id": 395, "major": "Business Development" },
{ "id": 396, "major": "Support" },
{ "id": 397, "major": "Human Resources" },
{ "id": 398, "major": "Services" },
{ "id": 399, "major": "Human Resources" },
{ "id": 400, "major": "Services" },
{ "id": 401, "major": "Engineering" },
{ "id": 402, "major": "Accounting" },
{ "id": 403, "major": "Training" },
{ "id": 404, "major": "Marketing" },
{ "id": 405, "major": "Services" },
{ "id": 406, "major": "Sales" },
{ "id": 407, "major": "Business Development" },
{ "id": 408, "major": "Accounting" },
{ "id": 409, "major": "Marketing" },
{ "id": 410, "major": "Accounting" },
{ "id": 411, "major": "Human Resources" },
{ "id": 412, "major": "Business Development" },
{ "id": 413, "major": "Sales" },
{ "id": 414, "major": "Legal" },
{ "id": 415, "major": "Services" },
{ "id": 416, "major": "Sales" },
{ "id": 417, "major": "Marketing" },
{ "id": 418, "major": "Support" },
{ "id": 419, "major": "Sales" },
{ "id": 420, "major": "Services" },
{ "id": 421, "major": "Training" },
{ "id": 422, "major": "Support" },
{ "id": 423, "major": "Accounting" },
{ "id": 424, "major": "Human Resources" },
{ "id": 425, "major": "Training" },
{ "id": 426, "major": "Research and Development" },
{ "id": 427, "major": "Training" },
{ "id": 428, "major": "Training" },
{ "id": 429, "major": "Accounting" },
{ "id": 430, "major": "Product Management" },
{ "id": 431, "major": "Marketing" },
{ "id": 432, "major": "Support" },
{ "id": 433, "major": "Accounting" },
{ "id": 434, "major": "Marketing" },
{ "id": 435, "major": "Research and Development" },
{ "id": 436, "major": "Sales" },
{ "id": 437, "major": "Marketing" },
{ "id": 438, "major": "Services" },
{ "id": 439, "major": "Engineering" },
{ "id": 440, "major": "Legal" },
{ "id": 441, "major": "Marketing" },
{ "id": 442, "major": "Accounting" },
{ "id": 443, "major": "Marketing" },
{ "id": 444, "major": "Product Management" },
{ "id": 445, "major": "Human Resources" },
{ "id": 446, "major": "Legal" },
{ "id": 447, "major": "Training" },
{ "id": 448, "major": "Training" },
{ "id": 449, "major": "Accounting" },
{ "id": 450, "major": "Training" },
{ "id": 451, "major": "Marketing" },
{ "id": 452, "major": "Marketing" },
{ "id": 453, "major": "Legal" },
{ "id": 454, "major": "Engineering" },
{ "id": 455, "major": "Business Development" },
{ "id": 456, "major": "Sales" },
{ "id": 457, "major": "Marketing" },
{ "id": 458, "major": "Legal" },
{ "id": 459, "major": "Accounting" },
{ "id": 460, "major": "Human Resources" },
{ "id": 461, "major": "Legal" },
{ "id": 462, "major": "Research and Development" },
{ "id": 463, "major": "Engineering" },
{ "id": 464, "major": "Product Management" },
{ "id": 465, "major": "Human Resources" },
{ "id": 466, "major": "Research and Development" },
{ "id": 467, "major": "Business Development" },
{ "id": 468, "major": "Services" },
{ "id": 469, "major": "Engineering" },
{ "id": 470, "major": "Sales" },
{ "id": 471, "major": "Training" },
{ "id": 472, "major": "Accounting" },
{ "id": 473, "major": "Training" },
{ "id": 474, "major": "Business Development" },
{ "id": 475, "major": "Services" },
{ "id": 476, "major": "Business Development" },
{ "id": 477, "major": "Marketing" },
{ "id": 478, "major": "Support" },
{ "id": 479, "major": "Training" },
{ "id": 480, "major": "Sales" },
{ "id": 481, "major": "Support" },
{ "id": 482, "major": "Marketing" },
{ "id": 483, "major": "Engineering" },
{ "id": 484, "major": "Legal" },
{ "id": 485, "major": "Support" },
{ "id": 486, "major": "Human Resources" },
{ "id": 487, "major": "Human Resources" },
{ "id": 488, "major": "Accounting" },
{ "id": 489, "major": "Marketing" },
{ "id": 490, "major": "Legal" },
{ "id": 491, "major": "Training" },
{ "id": 492, "major": "Business Development" },
{ "id": 493, "major": "Product Management" },
{ "id": 494, "major": "Research and Development" },
{ "id": 495, "major": "Product Management" },
{ "id": 496, "major": "Product Management" },
{ "id": 497, "major": "Training" },
{ "id": 498, "major": "Training" },
{ "id": 499, "major": "Marketing" },
{ "id": 500, "major": "Support" },
{ "id": 501, "major": "Legal" },
{ "id": 502, "major": "Human Resources" },
{ "id": 503, "major": "Support" },
{ "id": 504, "major": "Research and Development" },
{ "id": 505, "major": "Marketing" },
{ "id": 506, "major": "Legal" },
{ "id": 507, "major": "Support" },
{ "id": 508, "major": "Legal" },
{ "id": 509, "major": "Marketing" },
{ "id": 510, "major": "Product Management" },
{ "id": 511, "major": "Research and Development" },
{ "id": 512, "major": "Business Development" },
{ "id": 513, "major": "Human Resources" },
{ "id": 514, "major": "Training" },
{ "id": 515, "major": "Marketing" },
{ "id": 516, "major": "Training" },
{ "id": 517, "major": "Marketing" },
{ "id": 518, "major": "Research and Development" },
{ "id": 519, "major": "Business Development" },
{ "id": 520, "major": "Training" },
{ "id": 521, "major": "Services" },
{ "id": 522, "major": "Business Development" },
{ "id": 523, "major": "Human Resources" },
{ "id": 524, "major": "Product Management" },
{ "id": 525, "major": "Support" },
{ "id": 526, "major": "Services" },
{ "id": 527, "major": "Engineering" },
{ "id": 528, "major": "Research and Development" },
{ "id": 529, "major": "Support" },
{ "id": 530, "major": "Training" },
{ "id": 531, "major": "Legal" },
{ "id": 532, "major": "Services" },
{ "id": 533, "major": "Sales" },
{ "id": 534, "major": "Legal" },
{ "id": 535, "major": "Product Management" },
{ "id": 536, "major": "Business Development" },
{ "id": 537, "major": "Engineering" },
{ "id": 538, "major": "Business Development" },
{ "id": 539, "major": "Business Development" },
{ "id": 540, "major": "Support" },
{ "id": 541, "major": "Sales" },
{ "id": 542, "major": "Training" },
{ "id": 543, "major": "Legal" },
{ "id": 544, "major": "Business Development" },
{ "id": 545, "major": "Engineering" },
{ "id": 546, "major": "Research and Development" },
{ "id": 547, "major": "Support" },
{ "id": 548, "major": "Research and Development" },
{ "id": 549, "major": "Product Management" },
{ "id": 550, "major": "Support" },
{ "id": 551, "major": "Sales" },
{ "id": 552, "major": "Marketing" },
{ "id": 553, "major": "Human Resources" },
{ "id": 554, "major": "Sales" },
{ "id": 555, "major": "Research and Development" },
{ "id": 556, "major": "Accounting" },
{ "id": 557, "major": "Legal" },
{ "id": 558, "major": "Marketing" },
{ "id": 559, "major": "Services" },
{ "id": 560, "major": "Sales" },
{ "id": 561, "major": "Services" },
{ "id": 562, "major": "Sales" },
{ "id": 563, "major": "Sales" },
{ "id": 564, "major": "Accounting" },
{ "id": 565, "major": "Support" },
{ "id": 566, "major": "Sales" },
{ "id": 567, "major": "Research and Development" },
{ "id": 568, "major": "Product Management" },
{ "id": 569, "major": "Marketing" },
{ "id": 570, "major": "Training" },
{ "id": 571, "major": "Business Development" },
{ "id": 572, "major": "Services" },
{ "id": 573, "major": "Business Development" },
{ "id": 574, "major": "Human Resources" },
{ "id": 575, "major": "Support" },
{ "id": 576, "major": "Marketing" },
{ "id": 577, "major": "Training" },
{ "id": 578, "major": "Business Development" },
{ "id": 579, "major": "Human Resources" },
{ "id": 580, "major": "Support" },
{ "id": 581, "major": "Support" },
{ "id": 582, "major": "Training" },
{ "id": 583, "major": "Support" },
{ "id": 584, "major": "Marketing" },
{ "id": 585, "major": "Business Development" },
{ "id": 586, "major": "Accounting" },
{ "id": 587, "major": "Training" },
{ "id": 588, "major": "Business Development" },
{ "id": 589, "major": "Engineering" },
{ "id": 590, "major": "Training" },
{ "id": 591, "major": "Services" },
{ "id": 592, "major": "Product Management" },
{ "id": 593, "major": "Training" },
{ "id": 594, "major": "Support" },
{ "id": 595, "major": "Business Development" },
{ "id": 596, "major": "Human Resources" },
{ "id": 597, "major": "Training" },
{ "id": 598, "major": "Support" },
{ "id": 599, "major": "Sales" },
{ "id": 600, "major": "Training" },
{ "id": 601, "major": "Engineering" },
{ "id": 602, "major": "Research and Development" },
{ "id": 603, "major": "Marketing" },
{ "id": 604, "major": "Human Resources" },
{ "id": 605, "major": "Support" },
{ "id": 606, "major": "Sales" },
{ "id": 607, "major": "Legal" },
{ "id": 608, "major": "Engineering" },
{ "id": 609, "major": "Sales" },
{ "id": 610, "major": "Training" },
{ "id": 611, "major": "Product Management" },
{ "id": 612, "major": "Training" },
{ "id": 613, "major": "Business Development" },
{ "id": 614, "major": "Legal" },
{ "id": 615, "major": "Human Resources" },
{ "id": 616, "major": "Training" },
{ "id": 617, "major": "Human Resources" },
{ "id": 618, "major": "Services" },
{ "id": 619, "major": "Research and Development" },
{ "id": 620, "major": "Services" },
{ "id": 621, "major": "Human Resources" },
{ "id": 622, "major": "Engineering" },
{ "id": 623, "major": "Sales" },
{ "id": 624, "major": "Sales" },
{ "id": 625, "major": "Legal" },
{ "id": 626, "major": "Research and Development" },
{ "id": 627, "major": "Product Management" },
{ "id": 628, "major": "Services" },
{ "id": 629, "major": "Marketing" },
{ "id": 630, "major": "Legal" },
{ "id": 631, "major": "Research and Development" },
{ "id": 632, "major": "Marketing" },
{ "id": 633, "major": "Support" },
{ "id": 634, "major": "Legal" },
{ "id": 635, "major": "Support" },
{ "id": 636, "major": "Accounting" },
{ "id": 637, "major": "Accounting" },
{ "id": 638, "major": "Research and Development" },
{ "id": 639, "major": "Engineering" },
{ "id": 640, "major": "Support" },
{ "id": 641, "major": "Support" },
{ "id": 642, "major": "Business Development" },
{ "id": 643, "major": "Human Resources" },
{ "id": 644, "major": "Human Resources" },
{ "id": 645, "major": "Research and Development" },
{ "id": 646, "major": "Marketing" },
{ "id": 647, "major": "Research and Development" },
{ "id": 648, "major": "Engineering" },
{ "id": 649, "major": "Accounting" },
{ "id": 650, "major": "Marketing" },
{ "id": 651, "major": "Sales" },
{ "id": 652, "major": "Research and Development" },
{ "id": 653, "major": "Accounting" },
{ "id": 654, "major": "Business Development" },
{ "id": 655, "major": "Services" },
{ "id": 656, "major": "Engineering" },
{ "id": 657, "major": "Legal" },
{ "id": 658, "major": "Support" },
{ "id": 659, "major": "Engineering" },
{ "id": 660, "major": "Human Resources" },
{ "id": 661, "major": "Product Management" },
{ "id": 662, "major": "Engineering" },
{ "id": 663, "major": "Services" },
{ "id": 664, "major": "Accounting" },
{ "id": 665, "major": "Services" },
{ "id": 666, "major": "Product Management" },
{ "id": 667, "major": "Marketing" },
{ "id": 668, "major": "Services" },
{ "id": 669, "major": "Legal" },
{ "id": 670, "major": "Training" },
{ "id": 671, "major": "Business Development" },
{ "id": 672, "major": "Services" },
{ "id": 673, "major": "Legal" },
{ "id": 674, "major": "Training" },
{ "id": 675, "major": "Marketing" },
{ "id": 676, "major": "Business Development" },
{ "id": 677, "major": "Sales" },
{ "id": 678, "major": "Services" },
{ "id": 679, "major": "Product Management" },
{ "id": 680, "major": "Marketing" },
{ "id": 681, "major": "Support" },
{ "id": 682, "major": "Business Development" },
{ "id": 683, "major": "Support" },
{ "id": 684, "major": "Support" },
{ "id": 685, "major": "Legal" },
{ "id": 686, "major": "Sales" },
{ "id": 687, "major": "Product Management" },
{ "id": 688, "major": "Engineering" },
{ "id": 689, "major": "Support" },
{ "id": 690, "major": "Services" },
{ "id": 691, "major": "Services" },
{ "id": 692, "major": "Training" },
{ "id": 693, "major": "Services" },
{ "id": 694, "major": "Business Development" },
{ "id": 695, "major": "Business Development" },
{ "id": 696, "major": "Support" },
{ "id": 697, "major": "Human Resources" },
{ "id": 698, "major": "Legal" },
{ "id": 699, "major": "Legal" },
{ "id": 700, "major": "Product Management" },
{ "id": 701, "major": "Training" },
{ "id": 702, "major": "Legal" },
{ "id": 703, "major": "Training" },
{ "id": 704, "major": "Services" },
{ "id": 705, "major": "Legal" },
{ "id": 706, "major": "Engineering" },
{ "id": 707, "major": "Engineering" },
{ "id": 708, "major": "Legal" },
{ "id": 709, "major": "Human Resources" },
{ "id": 710, "major": "Accounting" },
{ "id": 711, "major": "Support" },
{ "id": 712, "major": "Product Management" },
{ "id": 713, "major": "Accounting" },
{ "id": 714, "major": "Accounting" },
{ "id": 715, "major": "Training" },
{ "id": 716, "major": "Legal" },
{ "id": 717, "major": "Business Development" },
{ "id": 718, "major": "Marketing" },
{ "id": 719, "major": "Research and Development" },
{ "id": 720, "major": "Human Resources" },
{ "id": 721, "major": "Legal" },
{ "id": 722, "major": "Accounting" },
{ "id": 723, "major": "Training" },
{ "id": 724, "major": "Engineering" },
{ "id": 725, "major": "Legal" },
{ "id": 726, "major": "Services" },
{ "id": 727, "major": "Marketing" },
{ "id": 728, "major": "Legal" },
{ "id": 729, "major": "Business Development" },
{ "id": 730, "major": "Accounting" },
{ "id": 731, "major": "Engineering" },
{ "id": 732, "major": "Research and Development" },
{ "id": 733, "major": "Human Resources" },
{ "id": 734, "major": "Training" },
{ "id": 735, "major": "Marketing" },
{ "id": 736, "major": "Sales" },
{ "id": 737, "major": "Legal" },
{ "id": 738, "major": "Training" },
{ "id": 739, "major": "Research and Development" },
{ "id": 740, "major": "Services" },
{ "id": 741, "major": "Business Development" },
{ "id": 742, "major": "Product Management" },
{ "id": 743, "major": "Legal" },
{ "id": 744, "major": "Legal" },
{ "id": 745, "major": "Product Management" },
{ "id": 746, "major": "Human Resources" },
{ "id": 747, "major": "Services" },
{ "id": 748, "major": "Accounting" },
{ "id": 749, "major": "Services" },
{ "id": 750, "major": "Training" },
{ "id": 751, "major": "Marketing" },
{ "id": 752, "major": "Sales" },
{ "id": 753, "major": "Legal" },
{ "id": 754, "major": "Research and Development" },
{ "id": 755, "major": "Research and Development" },
{ "id": 756, "major": "Sales" },
{ "id": 757, "major": "Training" },
{ "id": 758, "major": "Legal" },
{ "id": 759, "major": "Product Management" },
{ "id": 760, "major": "Legal" },
{ "id": 761, "major": "Training" },
{ "id": 762, "major": "Sales" },
{ "id": 763, "major": "Legal" },
{ "id": 764, "major": "Support" },
{ "id": 765, "major": "Human Resources" },
{ "id": 766, "major": "Business Development" },
{ "id": 767, "major": "Human Resources" },
{ "id": 768, "major": "Marketing" },
{ "id": 769, "major": "Legal" },
{ "id": 770, "major": "Marketing" },
{ "id": 771, "major": "Research and Development" },
{ "id": 772, "major": "Human Resources" },
{ "id": 773, "major": "Product Management" },
{ "id": 774, "major": "Business Development" },
{ "id": 775, "major": "Human Resources" },
{ "id": 776, "major": "Marketing" },
{ "id": 777, "major": "Services" },
{ "id": 778, "major": "Sales" },
{ "id": 779, "major": "Engineering" },
{ "id": 780, "major": "Accounting" },
{ "id": 781, "major": "Services" },
{ "id": 782, "major": "Training" },
{ "id": 783, "major": "Product Management" },
{ "id": 784, "major": "Business Development" },
{ "id": 785, "major": "Human Resources" },
{ "id": 786, "major": "Sales" },
{ "id": 787, "major": "Training" },
{ "id": 788, "major": "Business Development" },
{ "id": 789, "major": "Accounting" },
{ "id": 790, "major": "Sales" },
{ "id": 791, "major": "Sales" },
{ "id": 792, "major": "Human Resources" },
{ "id": 793, "major": "Services" },
{ "id": 794, "major": "Accounting" },
{ "id": 795, "major": "Engineering" },
{ "id": 796, "major": "Legal" },
{ "id": 797, "major": "Product Management" },
{ "id": 798, "major": "Engineering" },
{ "id": 799, "major": "Services" },
{ "id": 800, "major": "Engineering" },
{ "id": 801, "major": "Marketing" },
{ "id": 802, "major": "Marketing" },
{ "id": 803, "major": "Accounting" },
{ "id": 804, "major": "Human Resources" },
{ "id": 805, "major": "Human Resources" },
{ "id": 806, "major": "Product Management" },
{ "id": 807, "major": "Legal" },
{ "id": 808, "major": "Legal" },
{ "id": 809, "major": "Business Development" },
{ "id": 810, "major": "Research and Development" },
{ "id": 811, "major": "Human Resources" },
{ "id": 812, "major": "Accounting" },
{ "id": 813, "major": "Business Development" },
{ "id": 814, "major": "Services" },
{ "id": 815, "major": "Product Management" },
{ "id": 816, "major": "Research and Development" },
{ "id": 817, "major": "Business Development" },
{ "id": 818, "major": "Research and Development" },
{ "id": 819, "major": "Human Resources" },
{ "id": 820, "major": "Product Management" },
{ "id": 821, "major": "Accounting" },
{ "id": 822, "major": "Accounting" },
{ "id": 823, "major": "Support" },
{ "id": 824, "major": "Marketing" },
{ "id": 825, "major": "Marketing" },
{ "id": 826, "major": "Engineering" },
{ "id": 827, "major": "Accounting" },
{ "id": 828, "major": "Services" },
{ "id": 829, "major": "Marketing" },
{ "id": 830, "major": "Product Management" },
{ "id": 831, "major": "Marketing" },
{ "id": 832, "major": "Research and Development" },
{ "id": 833, "major": "Human Resources" },
{ "id": 834, "major": "Accounting" },
{ "id": 835, "major": "Marketing" },
{ "id": 836, "major": "Research and Development" },
{ "id": 837, "major": "Training" },
{ "id": 838, "major": "Accounting" },
{ "id": 839, "major": "Marketing" },
{ "id": 840, "major": "Marketing" },
{ "id": 841, "major": "Legal" },
{ "id": 842, "major": "Marketing" },
{ "id": 843, "major": "Human Resources" },
{ "id": 844, "major": "Human Resources" },
{ "id": 845, "major": "Human Resources" },
{ "id": 846, "major": "Services" },
{ "id": 847, "major": "Human Resources" },
{ "id": 848, "major": "Business Development" },
{ "id": 849, "major": "Human Resources" },
{ "id": 850, "major": "Business Development" },
{ "id": 851, "major": "Marketing" },
{ "id": 852, "major": "Accounting" },
{ "id": 853, "major": "Marketing" },
{ "id": 854, "major": "Product Management" },
{ "id": 855, "major": "Research and Development" },
{ "id": 856, "major": "Support" },
{ "id": 857, "major": "Marketing" },
{ "id": 858, "major": "Research and Development" },
{ "id": 859, "major": "Marketing" },
{ "id": 860, "major": "Human Resources" },
{ "id": 861, "major": "Engineering" },
{ "id": 862, "major": "Engineering" },
{ "id": 863, "major": "Sales" },
{ "id": 864, "major": "Marketing" },
{ "id": 865, "major": "Research and Development" },
{ "id": 866, "major": "Marketing" },
{ "id": 867, "major": "Research and Development" },
{ "id": 868, "major": "Product Management" },
{ "id": 869, "major": "Support" },
{ "id": 870, "major": "Research and Development" },
{ "id": 871, "major": "Services" },
{ "id": 872, "major": "Accounting" },
{ "id": 873, "major": "Business Development" },
{ "id": 874, "major": "Marketing" },
{ "id": 875, "major": "Training" },
{ "id": 876, "major": "Marketing" },
{ "id": 877, "major": "Marketing" },
{ "id": 878, "major": "Legal" },
{ "id": 879, "major": "Marketing" },
{ "id": 880, "major": "Business Development" },
{ "id": 881, "major": "Accounting" },
{ "id": 882, "major": "Sales" },
{ "id": 883, "major": "Accounting" },
{ "id": 884, "major": "Services" },
{ "id": 885, "major": "Support" },
{ "id": 886, "major": "Human Resources" },
{ "id": 887, "major": "Engineering" },
{ "id": 888, "major": "Services" },
{ "id": 889, "major": "Support" },
{ "id": 890, "major": "Sales" },
{ "id": 891, "major": "Services" },
{ "id": 892, "major": "Sales" },
{ "id": 893, "major": "Engineering" },
{ "id": 894, "major": "Research and Development" },
{ "id": 895, "major": "Services" },
{ "id": 896, "major": "Research and Development" },
{ "id": 897, "major": "Legal" },
{ "id": 898, "major": "Research and Development" },
{ "id": 899, "major": "Research and Development" },
{ "id": 900, "major": "Legal" },
{ "id": 901, "major": "Business Development" },
{ "id": 902, "major": "Accounting" },
{ "id": 903, "major": "Product Management" },
{ "id": 904, "major": "Marketing" },
{ "id": 905, "major": "Sales" },
{ "id": 906, "major": "Engineering" },
{ "id": 907, "major": "Engineering" },
{ "id": 908, "major": "Support" },
{ "id": 909, "major": "Business Development" },
{ "id": 910, "major": "Support" },
{ "id": 911, "major": "Marketing" },
{ "id": 912, "major": "Business Development" },
{ "id": 913, "major": "Sales" },
{ "id": 914, "major": "Services" },
{ "id": 915, "major": "Marketing" },
{ "id": 916, "major": "Engineering" },
{ "id": 917, "major": "Services" },
{ "id": 918, "major": "Sales" },
{ "id": 919, "major": "Human Resources" },
{ "id": 920, "major": "Sales" },
{ "id": 921, "major": "Human Resources" },
{ "id": 922, "major": "Research and Development" },
{ "id": 923, "major": "Engineering" },
{ "id": 924, "major": "Research and Development" },
{ "id": 925, "major": "Human Resources" },
{ "id": 926, "major": "Training" },
{ "id": 927, "major": "Accounting" },
{ "id": 928, "major": "Support" },
{ "id": 929, "major": "Product Management" },
{ "id": 930, "major": "Business Development" },
{ "id": 931, "major": "Sales" },
{ "id": 932, "major": "Training" },
{ "id": 933, "major": "Legal" },
{ "id": 934, "major": "Product Management" },
{ "id": 935, "major": "Accounting" },
{ "id": 936, "major": "Human Resources" },
{ "id": 937, "major": "Engineering" },
{ "id": 938, "major": "Human Resources" },
{ "id": 939, "major": "Engineering" },
{ "id": 940, "major": "Research and Development" },
{ "id": 941, "major": "Accounting" },
{ "id": 942, "major": "Sales" },
{ "id": 943, "major": "Marketing" },
{ "id": 944, "major": "Human Resources" },
{ "id": 945, "major": "Support" },
{ "id": 946, "major": "Engineering" },
{ "id": 947, "major": "Product Management" },
{ "id": 948, "major": "Product Management" },
{ "id": 949, "major": "Engineering" },
{ "id": 950, "major": "Human Resources" },
{ "id": 951, "major": "Legal" },
{ "id": 952, "major": "Accounting" },
{ "id": 953, "major": "Marketing" },
{ "id": 954, "major": "Support" },
{ "id": 955, "major": "Accounting" },
{ "id": 956, "major": "Sales" },
{ "id": 957, "major": "Legal" },
{ "id": 958, "major": "Support" },
{ "id": 959, "major": "Sales" },
{ "id": 960, "major": "Support" },
{ "id": 961, "major": "Support" },
{ "id": 962, "major": "Services" },
{ "id": 963, "major": "Sales" },
{ "id": 964, "major": "Support" },
{ "id": 965, "major": "Training" },
{ "id": 966, "major": "Sales" },
{ "id": 967, "major": "Marketing" },
{ "id": 968, "major": "Engineering" },
{ "id": 969, "major": "Human Resources" },
{ "id": 970, "major": "Marketing" },
{ "id": 971, "major": "Human Resources" },
{ "id": 972, "major": "Sales" },
{ "id": 973, "major": "Services" },
{ "id": 974, "major": "Training" },
{ "id": 975, "major": "Human Resources" },
{ "id": 976, "major": "Accounting" },
{ "id": 977, "major": "Services" },
{ "id": 978, "major": "Marketing" },
{ "id": 979, "major": "Marketing" },
{ "id": 980, "major": "Legal" },
{ "id": 981, "major": "Sales" },
{ "id": 982, "major": "Product Management" },
{ "id": 983, "major": "Sales" },
{ "id": 984, "major": "Research and Development" },
{ "id": 985, "major": "Legal" },
{ "id": 986, "major": "Human Resources" },
{ "id": 987, "major": "Business Development" },
{ "id": 988, "major": "Marketing" },
{ "id": 989, "major": "Legal" },
{ "id": 990, "major": "Engineering" },
{ "id": 991, "major": "Research and Development" },
{ "id": 992, "major": "Human Resources" },
{ "id": 993, "major": "Engineering" },
{ "id": 994, "major": "Human Resources" },
{ "id": 995, "major": "Product Management" },
{ "id": 996, "major": "Human Resources" },
{ "id": 997, "major": "Services" },
{ "id": 998, "major": "Marketing" },
{ "id": 999, "major": "Training" },
{ "id": 1000, "major": "Research and Development" }]