export const schoolData = [{ "id": 1, "school": "Thainguyen University of Agriculture and Forestry" },
{ "id": 2, "school": "Ningbo University" },
{ "id": 3, "school": "University of Wisconsin - Superior" },
{ "id": 4, "school": "Ecole Nationale de la Statistique et de l'Administration Economique" },
{ "id": 5, "school": "Nara University of Commerce" },
{ "id": 6, "school": "Universitas Sarjanawiyata Tamansiswa" },
{ "id": 7, "school": "University of Houston, Clear Lake" },
{ "id": 8, "school": "Adventist University of Africa" },
{ "id": 9, "school": "Universiti Teknologi Petronas" },
{ "id": 10, "school": "Universität für künstlerische und industrielle Gestaltung Linz" },
{ "id": 11, "school": "Skrjabin Moscow State Academy of Veterinary Medicine and Biotechnology" },
{ "id": 12, "school": "Nakhchivan Private University" },
{ "id": 13, "school": "Pedagogical University of Krakow" },
{ "id": 14, "school": "Universidade Independente" },
{ "id": 15, "school": "Institute of Industrial Electronics Engineering" },
{ "id": 16, "school": "University of Lusaka" },
{ "id": 17, "school": "New Jersey City University" },
{ "id": 18, "school": "Sistan & Balouchestan University" },
{ "id": 19, "school": "Université Alioune Diop de Bambey" },
{ "id": 20, "school": "Universidad Pedagógica Experimental Libertador" },
{ "id": 21, "school": "Fachhochschulstudiengänge der Wiener Wirtschaft" },
{ "id": 22, "school": "Saratov State Socio-Economic University" },
{ "id": 23, "school": "University of Houston, Downtown" },
{ "id": 24, "school": "Universidad de Bogotá \"Jorge Tadeo Lozano\"" },
{ "id": 25, "school": "Medical University of Sofia" },
{ "id": 26, "school": "Polytechnic Institute of Milan" },
{ "id": 27, "school": "University of Texas Health Center at Houston" },
{ "id": 28, "school": "Tamagawa University" },
{ "id": 29, "school": "Urmia University" },
{ "id": 30, "school": "Pennsylvania State University - Milton S.Hershey Medical Center" },
{ "id": 31, "school": "Kyoto Pharmaceutical University" },
{ "id": 32, "school": "Fresno City College" },
{ "id": 33, "school": "University of Pula" },
{ "id": 34, "school": "Institut Supérieure d'Electronique de Paris" },
{ "id": 35, "school": "Kwara State Polytecnic" },
{ "id": 36, "school": "Islamic Azad University, Garmsar" },
{ "id": 37, "school": "West Bengal University of Technology" },
{ "id": 38, "school": "Universidad Centroamericana \"José Simeón Canas\"" },
{ "id": 39, "school": "Petru Maior University of Targu Mures" },
{ "id": 40, "school": "Ecole Catholique d'Arts & Metiers" },
{ "id": 41, "school": "University of Ruhuna" },
{ "id": 42, "school": "Universidad Ricardo Palma" },
{ "id": 43, "school": "University of Delhi" },
{ "id": 44, "school": "Hogeschool Inholland" },
{ "id": 45, "school": "Ranchi University" },
{ "id": 46, "school": "St. Elizabeth’s College of Health and Social Sciences in Bratislava" },
{ "id": 47, "school": "University of Negros Occidental-Recoletos" },
{ "id": 48, "school": "Ithaca College" },
{ "id": 49, "school": "Instituto Politécnico do Cávado e do Ave" },
{ "id": 50, "school": "Miami University of Ohio - Middletown" },
{ "id": 51, "school": "Fondazione Sacro Cuore" },
{ "id": 52, "school": "Fachhochschule Heilbronn, Hochschule für Technik und Wirtschaft" },
{ "id": 53, "school": "Universidad de Valparaiso" },
{ "id": 54, "school": "Africa International University" },
{ "id": 55, "school": "Universidad Santo Tomás" },
{ "id": 56, "school": "Libyan International Medical University (LIMU)" },
{ "id": 57, "school": "Mokpo National Maritime University" },
{ "id": 58, "school": "Royal Danish School of Pharmacy" },
{ "id": 59, "school": "Bangladesh Agricultural University" },
{ "id": 60, "school": "University of Insubria" },
{ "id": 61, "school": "Indian School of Business Management and Administration" },
{ "id": 62, "school": "Lamar University - Port Arthur" },
{ "id": 63, "school": "Universität Bremen" },
{ "id": 64, "school": "Shanghai Ocean University" },
{ "id": 65, "school": "University of Texas Health Center at Houston" },
{ "id": 66, "school": "Global Open University , Nagaland" },
{ "id": 67, "school": "Life Chiropractic College West" },
{ "id": 68, "school": "Noakhali University of Science and Technology" },
{ "id": 69, "school": "Göteborg University" },
{ "id": 70, "school": "Dana College" },
{ "id": 71, "school": "Cumhuriyet (Republik) University" },
{ "id": 72, "school": "Nepal Sanskrit University" },
{ "id": 73, "school": "Shanghai Sipo Polytechnic" },
{ "id": 74, "school": "The Federal Polytechnic Offa" },
{ "id": 75, "school": "Hogeschool Rotterdam" },
{ "id": 76, "school": "Universidad San Francisco Xavier" },
{ "id": 77, "school": "Elisabeth University of Music" },
{ "id": 78, "school": "Fachhochschule Hof" },
{ "id": 79, "school": "Fachhochschule Vorarlberg" },
{ "id": 80, "school": "Instituto Politécnico de Setúbal" },
{ "id": 81, "school": "Kafr El-Sheikh University" },
{ "id": 82, "school": "Kostroma State Technological University" },
{ "id": 83, "school": "College of Technology at Kharj" },
{ "id": 84, "school": "Dominican College of Philosophy and Theology" },
{ "id": 85, "school": "Balochistan University of Engineering and Technology Khuzdar" },
{ "id": 86, "school": "University of Architecture, Civil Engineering and Geodesy" },
{ "id": 87, "school": "Fundación Universitaria Manuela Beltrán" },
{ "id": 88, "school": "Afe Babalola University" },
{ "id": 89, "school": "Belarussian State Agrarian Technical University" },
{ "id": 90, "school": "Hyogo College of Medicine" },
{ "id": 91, "school": "Kyushu University" },
{ "id": 92, "school": "University of Media Arts" },
{ "id": 93, "school": "Slobomir P Univerzitet" },
{ "id": 94, "school": "Upper Nile University" },
{ "id": 95, "school": "Capital Normal University" },
{ "id": 96, "school": "Université d'Alger" },
{ "id": 97, "school": "British College of Osteopathic Medicine" },
{ "id": 98, "school": "Universidad Pontificia Comillas" },
{ "id": 99, "school": "Instituto Universitario de Estudios Navales y Marítimos" },
{ "id": 100, "school": "International Academy of  Merchandising and Design Tampa" },
{ "id": 101, "school": "University of Cebu" },
{ "id": 102, "school": "Earlham College" },
{ "id": 103, "school": "Staatliche Hochschule für Musik" },
{ "id": 104, "school": "Posts & Telecommunications Institute of Technology" },
{ "id": 105, "school": "Wimbledon School of Art" },
{ "id": 106, "school": "Universidade São Marcos" },
{ "id": 107, "school": "Northern Virginia Community College" },
{ "id": 108, "school": "American University" },
{ "id": 109, "school": "Information and Communications University" },
{ "id": 110, "school": "University of Rajasthan" },
{ "id": 111, "school": "Sri Krishnadevaraya University" },
{ "id": 112, "school": "Silliman University" },
{ "id": 113, "school": "Aichi Medical University" },
{ "id": 114, "school": "University of Saint La Salle" },
{ "id": 115, "school": "Kigali Institute of Science & Technology" },
{ "id": 116, "school": "Southwest University of Nationalities" },
{ "id": 117, "school": "Centro Universitario Ciudad Vieja" },
{ "id": 118, "school": "New England School of Art and Design" },
{ "id": 119, "school": "Universidade de Caxias do Sul" },
{ "id": 120, "school": "Odense University" },
{ "id": 121, "school": "Kwame Nkrumah University of Science and Technology" },
{ "id": 122, "school": "The Southern Christian University" },
{ "id": 123, "school": "Polotsk State University" },
{ "id": 124, "school": "Universidad Andina Nestor Caceares Velasquez" },
{ "id": 125, "school": "Tokyo Metropolitan University of Health Sciences" },
{ "id": 126, "school": "Universidad Católica Popular del Risaralda" },
{ "id": 127, "school": "Tyumen State Agricultural Academy" },
{ "id": 128, "school": "Carnegie Mellon University" },
{ "id": 129, "school": "Universidad de Ciencias de la Informatica" },
{ "id": 130, "school": "Higher School o Business/National Louis University(WSB/NLU) in Nowy Sacz" },
{ "id": 131, "school": "Dalian Medical University" },
{ "id": 132, "school": "Nanjing Union Theological Seminary" },
{ "id": 133, "school": "Kuban State University" },
{ "id": 134, "school": "ENIC Telecom Lille 1" },
{ "id": 135, "school": "Université Lumière de Bujumbura" },
{ "id": 136, "school": "Brac University" },
{ "id": 137, "school": "Al Ghurair University" },
{ "id": 138, "school": "Zhongnan University of Technology" },
{ "id": 139, "school": "Université Mouloud Mammeri de Tizi Ouzou" },
{ "id": 140, "school": "Universidade Federal do Rio Grande do Norte" },
{ "id": 141, "school": "Coe College" },
{ "id": 142, "school": "Berea College" },
{ "id": 143, "school": "Alaska Pacific University" },
{ "id": 144, "school": "University of Seychelles - American Institute of Medicine" },
{ "id": 145, "school": "City University of New York, School of Law at Queens College" },
{ "id": 146, "school": "Akhbar El Yom Academy" },
{ "id": 147, "school": "Sudan Academy of Sciences" },
{ "id": 148, "school": "Institute of Information Technology" },
{ "id": 149, "school": "University of Petrosani" },
{ "id": 150, "school": "Guangdong University of Technology" },
{ "id": 151, "school": "University of California, Oakland" },
{ "id": 152, "school": "Indira Gandhi Institute of Medical Sciences" },
{ "id": 153, "school": "CollegeAmerica, Denver" },
{ "id": 154, "school": "University of Priština" },
{ "id": 155, "school": "East-Siberian State University" },
{ "id": 156, "school": "Andon College - Modesto" },
{ "id": 157, "school": "Baker College of Owosso" },
{ "id": 158, "school": "Rasmussen College, Wisconsin Campuses" },
{ "id": 159, "school": "National University of Science and Technology" },
{ "id": 160, "school": "New Mexico Institute of Mining and Technology" },
{ "id": 161, "school": "Surugadai University" },
{ "id": 162, "school": "Claremont Lincoln University" },
{ "id": 163, "school": "Shanghai University of Finance and Economics" },
{ "id": 164, "school": "Lamphun College of Agriculture and Technology" },
{ "id": 165, "school": "Technical University of Denmark" },
{ "id": 166, "school": "Wudanshan Taoist College " },
{ "id": 167, "school": "University of Waikato" },
{ "id": 168, "school": "Luhansk Taras Shevchenko National Pedagogical University" },
{ "id": 169, "school": "Police Academy of Latvia" },
{ "id": 170, "school": "Kyonggi University" },
{ "id": 171, "school": "University of Piraeus" },
{ "id": 172, "school": "Pedagogical University of Zielona Gora" },
{ "id": 173, "school": "Indian School of Mines (ISM)" },
{ "id": 174, "school": "Benedictine University, Springfield College in Illinois" },
{ "id": 175, "school": "Charisma University" },
{ "id": 176, "school": "Anna University of Technology, Tirunelveli" },
{ "id": 177, "school": "North Carolina Central University" },
{ "id": 178, "school": "University of Plymouth" },
{ "id": 179, "school": "Horizon College of Business and Technology" },
{ "id": 180, "school": "Hebei Agricultural University" },
{ "id": 181, "school": "Chowan College" },
{ "id": 182, "school": "DeVry Institute of Technology, Columbus" },
{ "id": 183, "school": "African Virtual University" },
{ "id": 184, "school": "Friends University" },
{ "id": 185, "school": "Institute of Public Administration" },
{ "id": 186, "school": "Emily Carr Institute of Art + Design" },
{ "id": 187, "school": "Ecole Supérieure d'Informatique-Electronique-Automatique" },
{ "id": 188, "school": "Nanjing Union Theological Seminary" },
{ "id": 189, "school": "Physical Education Academy \"Jozef Pilsudski\" in Warsaw" },
{ "id": 190, "school": "National University of Music" },
{ "id": 191, "school": "Vinnica National Technical University" },
{ "id": 192, "school": "Universitas Islam Nusantara" },
{ "id": 193, "school": "Capella University" },
{ "id": 194, "school": "Butler University" },
{ "id": 195, "school": "Central Academy of  Fine Art" },
{ "id": 196, "school": "Texas A&M University - Corpus Christi" },
{ "id": 197, "school": "DIPLOMA-Fachhochschule Ölsnitz/Vogtland" },
{ "id": 198, "school": "Tver State Medical Academy" },
{ "id": 199, "school": "Universidad Internacional de Andalucía, Sede Antonio Machado de Baeza" },
{ "id": 200, "school": "Evangelische Fachhochschule Freiburg, Hochschule für Soziale Arbeit, Diakonie und Religionspädagogik" },
{ "id": 201, "school": "University of Maine (System)" },
{ "id": 202, "school": "National Chengchi University" },
{ "id": 203, "school": "Bates College" },
{ "id": 204, "school": "Foundation University" },
{ "id": 205, "school": "Katholieke Universiteit Leuven, Campus Kortrijk" },
{ "id": 206, "school": "King's College" },
{ "id": 207, "school": "Universidad San Ignacio de Loyola" },
{ "id": 208, "school": "Université de Perpignan" },
{ "id": 209, "school": "National College of Art and Design" },
{ "id": 210, "school": "Osaka Gakuin University" },
{ "id": 211, "school": "Beijing University of Chinese Medicine and Pharmacology" },
{ "id": 212, "school": "Universidade Estadual de Ponta Grossa" },
{ "id": 213, "school": "Universidad Nacional Experimental \"Rafael Maria Baralt\"" },
{ "id": 214, "school": "Mercy College" },
{ "id": 215, "school": "University of Sassari" },
{ "id": 216, "school": "Aletheia University" },
{ "id": 217, "school": "West Virginia Wesleyan College" },
{ "id": 218, "school": "Evangelische Fachhochschule Berlin, Fachhochschule für Sozialarbeit und Sozialpädagogik" },
{ "id": 219, "school": "School of the Visual Arts" },
{ "id": 220, "school": "Ndejje University" },
{ "id": 221, "school": "Alfaisal University" },
{ "id": 222, "school": "Hungarian Academy of Craft and Design" },
{ "id": 223, "school": "Universitas Sebelas Maret" },
{ "id": 224, "school": "Columbia Commonwealth University" },
{ "id": 225, "school": "Wuhan University of Hydraulic and Electric Engineering" },
{ "id": 226, "school": "Universidade Católica de Pernambuco" },
{ "id": 227, "school": "Zanjan Institute for Advanced Studies in Basic Sciences" },
{ "id": 228, "school": "University of Detroit Mercy" },
{ "id": 229, "school": "Boston Architectural Center" },
{ "id": 230, "school": "University of Rijeka" },
{ "id": 231, "school": "Tomball College" },
{ "id": 232, "school": "Bengal Engineering College" },
{ "id": 233, "school": "Universidade Católica de Brasília" },
{ "id": 234, "school": "Tohoku Fukushi University" },
{ "id": 235, "school": "Central University of Finance and Economics" },
{ "id": 236, "school": "University of Central Greece" },
{ "id": 237, "school": "Lourdes College" },
{ "id": 238, "school": "Asian University of Bangladesh" },
{ "id": 239, "school": "Universidad Don Bosco" },
{ "id": 240, "school": "Technical University of Warsaw" },
{ "id": 241, "school": "Balochistan University of Engineering and Technology Khuzdar" },
{ "id": 242, "school": "The College of Santa Fe" },
{ "id": 243, "school": "Chamreun University of Poly Technology" },
{ "id": 244, "school": "Mohi-ud-Din Islamic University" },
{ "id": 245, "school": "Kyushu International University" },
{ "id": 246, "school": "Montreat College" },
{ "id": 247, "school": "University of the Humanities" },
{ "id": 248, "school": "Universidade para o Desenvolvimento do Alto Vale do Itajaí" },
{ "id": 249, "school": "Covenant College" },
{ "id": 250, "school": "Randolph-Macon Woman's College" },
{ "id": 251, "school": "Shenyang Polytechnic University" },
{ "id": 252, "school": "Tomsk State University of Control Systems and Radioelectronics" },
{ "id": 253, "school": "Pfeiffer University" },
{ "id": 254, "school": "Aktau State University" },
{ "id": 255, "school": "Renmin University of China" },
{ "id": 256, "school": "University of Perpetual Help" },
{ "id": 257, "school": "Universiti Pendidikan Sultan Idris" },
{ "id": 258, "school": "McMurry University" },
{ "id": 259, "school": "Loras College" },
{ "id": 260, "school": "Franklin College Switzerland" },
{ "id": 261, "school": "United States Military Academy" },
{ "id": 262, "school": "University of New Brunswick" },
{ "id": 263, "school": "Escuela Agricola Panamericana Zamorano" },
{ "id": 264, "school": "University of Resita" },
{ "id": 265, "school": "American College Of Dubai" },
{ "id": 266, "school": "University of National and World Economy" },
{ "id": 267, "school": "Hankyong National University" },
{ "id": 268, "school": "Universidad Católica Madre y Maestra" },
{ "id": 269, "school": "Wageningen University" },
{ "id": 270, "school": "Universidade Federal Rural de Pernambuco" },
{ "id": 271, "school": "University of Bristol" },
{ "id": 272, "school": "University of Technology - Iraq" },
{ "id": 273, "school": "Mandhu College" },
{ "id": 274, "school": "University of the West of England, Bristol" },
{ "id": 275, "school": "Kateb Institute of Higher Education" },
{ "id": 276, "school": "Loras College" },
{ "id": 277, "school": "University Of Dubai" },
{ "id": 278, "school": "Universitas Lancang Kuning" },
{ "id": 279, "school": "Perm State Medical Academy" },
{ "id": 280, "school": "Mansfield University of Pennsylvania" },
{ "id": 281, "school": "William Jewell College" },
{ "id": 282, "school": "Hirosaki Gakuin University" },
{ "id": 283, "school": "Qufu Normal University" },
{ "id": 284, "school": "Mizan Tepi University" },
{ "id": 285, "school": "Allen University" },
{ "id": 286, "school": "Universitas Katolik Parahyangan" },
{ "id": 287, "school": "Mount Ida College" },
{ "id": 288, "school": "Government College University Faisalabad" },
{ "id": 289, "school": "Free University Stockholm" },
{ "id": 290, "school": "Elms College" },
{ "id": 291, "school": "University of Sierra Leone" },
{ "id": 292, "school": "University of Medicine and Pharmacy of Targu Mures" },
{ "id": 293, "school": "Art University" },
{ "id": 294, "school": "Tashkent State University of Economics" },
{ "id": 295, "school": "European Academy of Arts in Warsaw" },
{ "id": 296, "school": "China Medical College" },
{ "id": 297, "school": "Staatlich anerkannte Fachhochschule für Kunsttherapie" },
{ "id": 298, "school": "Middle Tennessee State University" },
{ "id": 299, "school": "Université Paris-Sorbonne (Paris IV)" },
{ "id": 300, "school": "Mercy College" },
{ "id": 301, "school": "Women's College of Fine Arts" },
{ "id": 302, "school": "Universidad de Almería" },
{ "id": 303, "school": "University of Zadar" },
{ "id": 304, "school": "Mohi-ud-Din Islamic University" },
{ "id": 305, "school": "Technical University of Lublin" },
{ "id": 306, "school": "Health sciences University of Mongolia" },
{ "id": 307, "school": "İstanbul Şehir University" },
{ "id": 308, "school": "Illinois College of Optometry" },
{ "id": 309, "school": "University of Al-Qadisiyah" },
{ "id": 310, "school": "Newman University" },
{ "id": 311, "school": "Universidad Monteávila" },
{ "id": 312, "school": "Perak Islamic College" },
{ "id": 313, "school": "University of Ferrara" },
{ "id": 314, "school": "Western Governors University" },
{ "id": 315, "school": "Bilkent University" },
{ "id": 316, "school": "Kharkiv National University of Radio Electronics" },
{ "id": 317, "school": "Skyline University College, Sharjah" },
{ "id": 318, "school": "Universitas Negeri Manado" },
{ "id": 319, "school": "East-Siberian State University" },
{ "id": 320, "school": "Free International University of Moldova" },
{ "id": 321, "school": "Shahrekord University of Medical Sciences" },
{ "id": 322, "school": "The Boston Conservatory" },
{ "id": 323, "school": "Greenheart Medical School" },
{ "id": 324, "school": "Iglobal University" },
{ "id": 325, "school": "Universidade Federal do Rio de Janeiro" },
{ "id": 326, "school": "Nanjing Forestry University" },
{ "id": 327, "school": "Université Ibn Toufail" },
{ "id": 328, "school": "Lincoln University" },
{ "id": 329, "school": "Vinoba Bhave University" },
{ "id": 330, "school": "Mount St. Mary's College California" },
{ "id": 331, "school": "Universidade Bandeirante de São Paulo" },
{ "id": 332, "school": "Chao Yang University of Science and Technology" },
{ "id": 333, "school": "Hokkaigakuen University" },
{ "id": 334, "school": "Duquesne University" },
{ "id": 335, "school": "Kwangwoon University" },
{ "id": 336, "school": "Asian Medical Institute" },
{ "id": 337, "school": "Universitas Islam Syekh-Yusuf " },
{ "id": 338, "school": "Instituto Superior D. Afonso III - INUAF" },
{ "id": 339, "school": "University of Constanta Medical School" },
{ "id": 340, "school": "British Columbia Open University" },
{ "id": 341, "school": "University of St. Thomas, St. Paul" },
{ "id": 342, "school": "Montana Tech" },
{ "id": 343, "school": "Bosaso College" },
{ "id": 344, "school": "Pes University" },
{ "id": 345, "school": "Hyrcania Institute of Higher Education" },
{ "id": 346, "school": "Bashkir State Medical University" },
{ "id": 347, "school": "Universidad Odontológica Dominicana" },
{ "id": 348, "school": "Estonian University of Life Sciences" },
{ "id": 349, "school": "Nippon Dental University" },
{ "id": 350, "school": "Universitas Bung Hatta" },
{ "id": 351, "school": "Madonna University" },
{ "id": 352, "school": "Far Eastern State Technical Fisheries University" },
{ "id": 353, "school": "Hebei Medical University" },
{ "id": 354, "school": "University Institute of Oriental Studies" },
{ "id": 355, "school": "University of Wassit" },
{ "id": 356, "school": "University of Andorra" },
{ "id": 357, "school": "Philippine Military Academy" },
{ "id": 358, "school": "Ama International University" },
{ "id": 359, "school": "Nukus State Teachers Training Institute" },
{ "id": 360, "school": "Catholic University in Ruzomberok" },
{ "id": 361, "school": "Escuela de Ingeniería de Antioquia" },
{ "id": 362, "school": "Gokhale Institute of Politics and Economics" },
{ "id": 363, "school": "Khazar University" },
{ "id": 364, "school": "Institute of Teachers Education, Tengku Ampuan Afzan" },
{ "id": 365, "school": "Universidad Autónoma de Ciudad Juárez" },
{ "id": 366, "school": "University of Notre Dame" },
{ "id": 367, "school": "Medizinische Universität Lübeck" },
{ "id": 368, "school": "Universidade Federal de Pelotas" },
{ "id": 369, "school": "Ecole Nationale Supérieure de Chimie de Toulouse" },
{ "id": 370, "school": "University of the West Indies, Cave Hill" },
{ "id": 371, "school": "Turar Ryskulov Kazakh Economic University" },
{ "id": 372, "school": "University of Dundee" },
{ "id": 373, "school": "Davenport College of Business, Lansing" },
{ "id": 374, "school": "Ecole Nationale Supérieure d'Arts et Métiers de Paris" },
{ "id": 375, "school": "Universidad del Pacifico" },
{ "id": 376, "school": "University of Massachusetts at Dartmouth" },
{ "id": 377, "school": "National Taiwan Ocean University" },
{ "id": 378, "school": "ifs University College" },
{ "id": 379, "school": "Washington State University, Spokane" },
{ "id": 380, "school": "San Joaquin College of Law" },
{ "id": 381, "school": "St. Petersburg State Mining Institute (Technical University)" },
{ "id": 382, "school": "Maseno University" },
{ "id": 383, "school": "Universidad Nacional de Tres de Febrero" },
{ "id": 384, "school": "Georgia College & State University" },
{ "id": 385, "school": "Guizhou University" },
{ "id": 386, "school": "Ecole Supérieure de Commerce de Sophia Antipolis" },
{ "id": 387, "school": "University College of Arts, Crafts and Design" },
{ "id": 388, "school": "New York Chiropractic College" },
{ "id": 389, "school": "North China Electric Power University" },
{ "id": 390, "school": "Abant Izzet Baysal University" },
{ "id": 391, "school": "Surugadai University" },
{ "id": 392, "school": "Dammam Community College" },
{ "id": 393, "school": "Hope International University" },
{ "id": 394, "school": "Royal University of Bhutan" },
{ "id": 395, "school": "Facultés Universitaires Catholiques de Mons" },
{ "id": 396, "school": "Centro Universitario Villanueva" },
{ "id": 397, "school": "Chongqing Wenli University" },
{ "id": 398, "school": "Universidad Nacional de Loja" },
{ "id": 399, "school": "Universidad Latina" },
{ "id": 400, "school": "Kamrah International Institute of Technology (KIIT)" },
{ "id": 401, "school": "Tianjin Open University" },
{ "id": 402, "school": "Tamkang University" },
{ "id": 403, "school": "Visvesvaraya National Institute of Technology" },
{ "id": 404, "school": "IE University" },
{ "id": 405, "school": "Southeastern Baptist College" },
{ "id": 406, "school": "Universidade do Rio de Janeiro" },
{ "id": 407, "school": "Universitas Bakrie" },
{ "id": 408, "school": "Bentley College" },
{ "id": 409, "school": "Central Agricultural University" },
{ "id": 410, "school": "Manhattan Christian College" },
{ "id": 411, "school": "Free University \"Maria Santissima Assunta\"" },
{ "id": 412, "school": "Whittier College" },
{ "id": 413, "school": "Tokyo Woman's Christian University" },
{ "id": 414, "school": "Polytechnic University, Long Island Campus" },
{ "id": 415, "school": "Université de Haute-Alsace" },
{ "id": 416, "school": "Bridgewater State College" },
{ "id": 417, "school": "University of California, Riverside" },
{ "id": 418, "school": "Sunmoon University" },
{ "id": 419, "school": "Universidad de Managua (U de M)" },
{ "id": 420, "school": "Tilka Manjhi Bhagalpur University" },
{ "id": 421, "school": "Luzhou Medical College" },
{ "id": 422, "school": "Music Academy in Cracow" },
{ "id": 423, "school": "Islamic Azad University, Tabriz" },
{ "id": 424, "school": "Alabama Agricultural and Mechanical University" },
{ "id": 425, "school": "Alexandria University" },
{ "id": 426, "school": "Hokkaido University of Health Sciences" },
{ "id": 427, "school": "Kobe International University" },
{ "id": 428, "school": "National Yang Ming Medical College" },
{ "id": 429, "school": "Taipei Municipal Teachers College" },
{ "id": 430, "school": "University of Wollongong" },
{ "id": 431, "school": "McGill University" },
{ "id": 432, "school": "Vitebsk State Technological University" },
{ "id": 433, "school": "Bank Street College of Education" },
{ "id": 434, "school": "Coventry University" },
{ "id": 435, "school": "Seneca College" },
{ "id": 436, "school": "Károl Gáspár University of the Reformed Church" },
{ "id": 437, "school": "Hamadan University of Medical Sciences" },
{ "id": 438, "school": "University of Molise" },
{ "id": 439, "school": "University of Petroleum (East China)" },
{ "id": 440, "school": "Universitas Bakrie" },
{ "id": 441, "school": "Otterbein College" },
{ "id": 442, "school": "Seton Hall University" },
{ "id": 443, "school": "University of Sharjah" },
{ "id": 444, "school": "College of the Ozarks" },
{ "id": 445, "school": "American University" },
{ "id": 446, "school": "Helsinki University of Technology" },
{ "id": 447, "school": "Salem University" },
{ "id": 448, "school": "Jiangxi University of Traditional Chinese Medicine" },
{ "id": 449, "school": "School of Management Fribourg" },
{ "id": 450, "school": "Brewton-Parker College" },
{ "id": 451, "school": "University of Texas at San Antonio" },
{ "id": 452, "school": "Xinjiang Normal University" },
{ "id": 453, "school": "University of Houston, Downtown" },
{ "id": 454, "school": "Albion College" },
{ "id": 455, "school": "Pázmány Péter Catholic University" },
{ "id": 456, "school": "Harris-Stowe State University" },
{ "id": 457, "school": "University of NorthWest" },
{ "id": 458, "school": "Randolph-Macon College" },
{ "id": 459, "school": "Université de Bouaké" },
{ "id": 460, "school": "Islamic Azad University, Najaf Abad" },
{ "id": 461, "school": "Nakamura Gakuen University" },
{ "id": 462, "school": "University of Malakand" },
{ "id": 463, "school": "Takestan Islamic Azad University" },
{ "id": 464, "school": "North Central College" },
{ "id": 465, "school": "Lillehammer University College" },
{ "id": 466, "school": "Université Laval" },
{ "id": 467, "school": "Thomas Jefferson University" },
{ "id": 468, "school": "Divine Word College" },
{ "id": 469, "school": "Setsunan University" },
{ "id": 470, "school": "American University in Cairo" },
{ "id": 471, "school": "All Nations University College" },
{ "id": 472, "school": "Ahmedabad University" },
{ "id": 473, "school": "Muscat College" },
{ "id": 474, "school": "National Institute of Education" },
{ "id": 475, "school": "Centenary College" },
{ "id": 476, "school": "Samarkand State University" },
{ "id": 477, "school": "Hariri Canadian University" },
{ "id": 478, "school": "European University Cyprus" },
{ "id": 479, "school": "Universidad Privada de Tacna" },
{ "id": 480, "school": "RCSI-Medical University of Bahrain" },
{ "id": 481, "school": "Kent State University - Trumbull" },
{ "id": 482, "school": "Badakhshan University" },
{ "id": 483, "school": "College of St. Joseph" },
{ "id": 484, "school": "Universidad Politecnica de Puerto Rico" },
{ "id": 485, "school": "Josai University" },
{ "id": 486, "school": "St.Kliment Ohridski University" },
{ "id": 487, "school": "Katholische Fachhochschule Freiburg, Hochschule für Sozialwesen, Religionspädagogik und Pflege" },
{ "id": 488, "school": "Dawat University" },
{ "id": 489, "school": "Illinois Valley Community College" },
{ "id": 490, "school": "Sunrise University Alwar" },
{ "id": 491, "school": "Kagoshima Women's College" },
{ "id": 492, "school": "Northern State University" },
{ "id": 493, "school": "Université Vincennes Saint-Denis (Paris VIII)" },
{ "id": 494, "school": "Jubail Industrial College" },
{ "id": 495, "school": "University for Humanistics (UH)" },
{ "id": 496, "school": "Universidad APEC" },
{ "id": 497, "school": "Central Bible College" },
{ "id": 498, "school": "Taegu National University of Education" },
{ "id": 499, "school": "Kawasaki Medical School" },
{ "id": 500, "school": "Matsuyama University" },
{ "id": 501, "school": "Aalborg Business College" },
{ "id": 502, "school": "Universidad Católica de Santa Fé" },
{ "id": 503, "school": "University of Siena" },
{ "id": 504, "school": "University of Foggia" },
{ "id": 505, "school": "Yale University" },
{ "id": 506, "school": "Tamagawa University" },
{ "id": 507, "school": "German University in Cairo" },
{ "id": 508, "school": "Instituto Tecnológico Autonómo de México" },
{ "id": 509, "school": "California School of Professional Psychology - Berkley/Alameda" },
{ "id": 510, "school": "Antioch New England Graduate School" },
{ "id": 511, "school": "University of the West Indies, Cave Hill" },
{ "id": 512, "school": "Nukus State Teachers Training Institute" },
{ "id": 513, "school": "COMSATS Institute of Information Technology" },
{ "id": 514, "school": "Asia University" },
{ "id": 515, "school": "North South University" },
{ "id": 516, "school": "Fort Lewis College" },
{ "id": 517, "school": "Kent State University - Salem" },
{ "id": 518, "school": "Muhimbili University of Health and Allied Sciences (MUHAS)" },
{ "id": 519, "school": "University of Grigol Robakidze" },
{ "id": 520, "school": "Dhirubhai Ambani Institute of Information and Communication Technology" },
{ "id": 521, "school": "Massachusetts College of Liberal Arts" },
{ "id": 522, "school": "George Brown College" },
{ "id": 523, "school": "Université d'Abobo-Adjamé" },
{ "id": 524, "school": "Mwalimu Nyerere Memorial Academy" },
{ "id": 525, "school": "Philosophisch-Theologisches Studium Erfurt, Staatlich anerkannte Wissenschaftliche Hochschule" },
{ "id": 526, "school": "Shri Mata Vaishno Devi University" },
{ "id": 527, "school": "Aligarh Muslim University" },
{ "id": 528, "school": "National Academy of Music \"Pantcho Vladigerov\"" },
{ "id": 529, "school": "Columbia University" },
{ "id": 530, "school": "Universidad Nacional del Comahue" },
{ "id": 531, "school": "Umm Al-Qura University" },
{ "id": 532, "school": "Universidad Nacional de Misiones" },
{ "id": 533, "school": "Jagiellonian University Cracow" },
{ "id": 534, "school": "Osaka Prefectural University" },
{ "id": 535, "school": "University of Seychelles - American Institute of Medicine" },
{ "id": 536, "school": "University of El Imam El Mahdi University" },
{ "id": 537, "school": "Ecole Centrale de Nantes" },
{ "id": 538, "school": "Capitol College" },
{ "id": 539, "school": "Federal Urdu University of Arts,Science and Technology" },
{ "id": 540, "school": "University of Perpetual Help, System Dalta" },
{ "id": 541, "school": "Rheinisch Westfälische Technische Hochschule Aachen" },
{ "id": 542, "school": "Universidad Nacional de Educación Enrique Guzmán y Valle" },
{ "id": 543, "school": "Business and Hotel Management School" },
{ "id": 544, "school": "Payap University Chaiang Mai" },
{ "id": 545, "school": "Universidad Católica de Cuenca" },
{ "id": 546, "school": "International Business University of Beijing" },
{ "id": 547, "school": "FAE Business School - Faculdade de Administração e Economia" },
{ "id": 548, "school": "Logan College of Chiropractic" },
{ "id": 549, "school": "Ecole Centrale d'Electronique - ECE" },
{ "id": 550, "school": "Waseda University" },
{ "id": 551, "school": "Abu Dhabi University" },
{ "id": 552, "school": "Universidade de Ribeirão Preto" },
{ "id": 553, "school": "University of Health Sciences" },
{ "id": 554, "school": "Institute Of Technology, Australia" },
{ "id": 555, "school": "Agricultural University of Wroclaw" },
{ "id": 556, "school": "Avicenna International College" },
{ "id": 557, "school": "City University of New York, Lehman College" },
{ "id": 558, "school": "Kota Bharu Polytechnic" },
{ "id": 559, "school": "Mindanao State University - Iligan Institute of Technology" },
{ "id": 560, "school": "Universidad Nacional Experimental del Táchira" },
{ "id": 561, "school": "Universidade Luterana do Brasil" },
{ "id": 562, "school": "Mahatma Gandhi Kashi Vidyapith " },
{ "id": 563, "school": "Liszt Ferenc Academy of Music Budapest" },
{ "id": 564, "school": "Dilla University" },
{ "id": 565, "school": "Nagpur University" },
{ "id": 566, "school": "Open University of Sudan (OUS)" },
{ "id": 567, "school": "Hankyong National University" },
{ "id": 568, "school": "Taegu University" },
{ "id": 569, "school": "Hansei University" },
{ "id": 570, "school": "Mugla University" },
{ "id": 571, "school": "University of Holy Quran and Islamic Siences" },
{ "id": 572, "school": "University of Trieste" },
{ "id": 573, "school": "University of Advancing Technology (UAT)" },
{ "id": 574, "school": "Toyama University of International Studies" },
{ "id": 575, "school": "Universidad de La Frontera" },
{ "id": 576, "school": "Universidad del Mar" },
{ "id": 577, "school": "Baker College of Port Huron" },
{ "id": 578, "school": "STMIK Sinar Nusantara" },
{ "id": 579, "school": "Fachhochschule Mannheim, Hochschule für Sozialwesen" },
{ "id": 580, "school": "Fachhochschule Gießen-Friedberg" },
{ "id": 581, "school": "St. Matthews University" },
{ "id": 582, "school": "University of Seychelles - American Institute of Medicine" },
{ "id": 583, "school": "University of Arkansas (System)" },
{ "id": 584, "school": "San Jose Christian College" },
{ "id": 585, "school": "Universidad Politécnica de El Salvador" },
{ "id": 586, "school": "Universidad del Valle de México" },
{ "id": 587, "school": "Bishop's University" },
{ "id": 588, "school": "Universitas Nasional Jakarta" },
{ "id": 589, "school": "College of DuPage" },
{ "id": 590, "school": "Laboratory Institute of Merchandising" },
{ "id": 591, "school": "University of Baltimore" },
{ "id": 592, "school": "Appalachian Bible College" },
{ "id": 593, "school": "Józef Tyszkiewicz College of Business and Computer Science in Bielsko-Biala" },
{ "id": 594, "school": "Grand Valley State University" },
{ "id": 595, "school": "Frederick University" },
{ "id": 596, "school": "Agricultural University of Wroclaw" },
{ "id": 597, "school": "Eastern Oregon University" },
{ "id": 598, "school": "Osaka Electro-Communication University" },
{ "id": 599, "school": "Huron University" },
{ "id": 600, "school": "Bugema University" },
{ "id": 601, "school": "Luhansk State Medical University" },
{ "id": 602, "school": "St. Joseph College of Nursing" },
{ "id": 603, "school": "Utah State University" },
{ "id": 604, "school": "Universidad Peruana de Ciencias e Informática" },
{ "id": 605, "school": "Mohan Lal Sukhadia University" },
{ "id": 606, "school": "Kyoto Gakuen University" },
{ "id": 607, "school": "Minia University" },
{ "id": 608, "school": "Maharishi University of Management" },
{ "id": 609, "school": "International Institute for Population Sciences" },
{ "id": 610, "school": "Skadron College" },
{ "id": 611, "school": "Antioch University Los Angeles" },
{ "id": 612, "school": "Christopher Newport University" },
{ "id": 613, "school": "Nishikyushu University" },
{ "id": 614, "school": "Karachi School of Art" },
{ "id": 615, "school": "Loughborough University" },
{ "id": 616, "school": "Hong Kong Baptist University" },
{ "id": 617, "school": "Marietta College" },
{ "id": 618, "school": "Institut d'Agriculture, de Technologie et d'Education de Kibungo" },
{ "id": 619, "school": "Khazar University" },
{ "id": 620, "school": "Oregon State University" },
{ "id": 621, "school": "University of Canberra" },
{ "id": 622, "school": "Grove City College" },
{ "id": 623, "school": "Université Panthéon-Sorbonne (Paris I)" },
{ "id": 624, "school": "Donetsk National Technical University" },
{ "id": 625, "school": "Ecole Nationale Vétérinaire de Toulouse" },
{ "id": 626, "school": "Athens School of Fine Arts" },
{ "id": 627, "school": "Cleveland Chiropractic College, Kansas City" },
{ "id": 628, "school": "Mohi-ud-Din Islamic University" },
{ "id": 629, "school": "Police Academy of Latvia" },
{ "id": 630, "school": "Bilkent University" },
{ "id": 631, "school": "Ural State Technical University" },
{ "id": 632, "school": "Stie Perbanas Surabaya" },
{ "id": 633, "school": "Royal Military Academy" },
{ "id": 634, "school": "Hitec University" },
{ "id": 635, "school": "Université de La Rochelle" },
{ "id": 636, "school": "Universidad de Carabobo" },
{ "id": 637, "school": "Florida Southern College" },
{ "id": 638, "school": "Szent István University" },
{ "id": 639, "school": "Universidad Nacional Experimental de la Fuerza Armada" },
{ "id": 640, "school": "Shannon College of Hotel Management" },
{ "id": 641, "school": "Kampala University" },
{ "id": 642, "school": "Luzhou Medical College" },
{ "id": 643, "school": "Full Sail University" },
{ "id": 644, "school": "Universitas Slamet Riyadi Surakarta" },
{ "id": 645, "school": "Evangelische Fachhochschule für Sozialpädagogik der \"Diakonenanstalt des Rauhen Hauses\" Hamburg" },
{ "id": 646, "school": "Elizabethtown College" },
{ "id": 647, "school": "Universidad Finis Terrae" },
{ "id": 648, "school": "Ningxia University" },
{ "id": 649, "school": "Institut National de la Recherche Scientifique, Université du Québec" },
{ "id": 650, "school": "French Institute of Management" },
{ "id": 651, "school": "Jahrom University of Medical Sciences" },
{ "id": 652, "school": "Benedictine University, Springfield College in Illinois" },
{ "id": 653, "school": "American College of Greece" },
{ "id": 654, "school": "University of Latvia" },
{ "id": 655, "school": "Wesleyan University Philippines" },
{ "id": 656, "school": "University of Colorado at Boulder" },
{ "id": 657, "school": "Concordia College, Seward" },
{ "id": 658, "school": "Dalhousie University" },
{ "id": 659, "school": "St. Petersburg State Pediatric Medical Academy" },
{ "id": 660, "school": "William Carey College" },
{ "id": 661, "school": "National Taiwan University of Science and Technology" },
{ "id": 662, "school": "University of Central Texas" },
{ "id": 663, "school": "University of Wales, Aberystwyth" },
{ "id": 664, "school": "Technische Universität München" },
{ "id": 665, "school": "Yanbian University of Science and Technology" },
{ "id": 666, "school": "College of New Caledonia" },
{ "id": 667, "school": "DeSales University" },
{ "id": 668, "school": "Pjatigorsk State Linguistic University" },
{ "id": 669, "school": "Universitas Proklamasi 45" },
{ "id": 670, "school": "Fiji School of Medicine" },
{ "id": 671, "school": "American University of Armenia" },
{ "id": 672, "school": "National University of Theater and Film Arts" },
{ "id": 673, "school": "Springfield College" },
{ "id": 674, "school": "Universidad Experimental Felix Adam" },
{ "id": 675, "school": "Inchon University" },
{ "id": 676, "school": "Water Resources University" },
{ "id": 677, "school": "Beijing Foreign Studies University" },
{ "id": 678, "school": "Bashkir State Agrarian University" },
{ "id": 679, "school": "Universidad Autónoma de Chihuahua" },
{ "id": 680, "school": "Universidad Dr. Rafael Belloso Chacín" },
{ "id": 681, "school": "Irkutsk State Technical University" },
{ "id": 682, "school": "Fachhochschule Dortmund" },
{ "id": 683, "school": "Lewis and Clark College" },
{ "id": 684, "school": "Central Washington University" },
{ "id": 685, "school": "St. Francis College, Fort Wayne" },
{ "id": 686, "school": "Hochschule für Berufstätige Rendsburg" },
{ "id": 687, "school": "Dalian University of Technology" },
{ "id": 688, "school": "East-West University" },
{ "id": 689, "school": "Tusculum College" },
{ "id": 690, "school": "Vitebsk State Technological University" },
{ "id": 691, "school": "Altai State University" },
{ "id": 692, "school": "Universidad de Piura" },
{ "id": 693, "school": "Tokyo Women's Medial College" },
{ "id": 694, "school": "Benguet State University" },
{ "id": 695, "school": "Mount Olive College" },
{ "id": 696, "school": "Pebble Hills University" },
{ "id": 697, "school": "Universitas Klabat" },
{ "id": 698, "school": "University of Akron" },
{ "id": 699, "school": "Universidad de Artes, Ciencias y Comunicación" },
{ "id": 700, "school": "Royal Academy of Music" },
{ "id": 701, "school": "Liaquat University of Medical & Health Sciences Jamshoro" },
{ "id": 702, "school": "Semmelweis University of Medical Sciences" },
{ "id": 703, "school": "Fukuoka University of Education" },
{ "id": 704, "school": "National Taras Shevchenko University of Kiev" },
{ "id": 705, "school": "Petru Maior University of Targu Mures" },
{ "id": 706, "school": "Shepherd College" },
{ "id": 707, "school": "Krishna University" },
{ "id": 708, "school": "Luxun Academy of Fine Art" },
{ "id": 709, "school": "Universidad Nacional Andrés Bello" },
{ "id": 710, "school": "National Museum Institute of History of Art, Conservation and Museology" },
{ "id": 711, "school": "Houston Baptist University" },
{ "id": 712, "school": "Université Alioune Diop de Bambey" },
{ "id": 713, "school": "Ecole Française d'Electronique et d'Informatique" },
{ "id": 714, "school": "Charles Sturt University" },
{ "id": 715, "school": "Universidad de Especialidades Turísticas " },
{ "id": 716, "school": "Shizuoka Prefectural University" },
{ "id": 717, "school": "Technische Fachhochschule Wildau" },
{ "id": 718, "school": "Dokuz Eylül University" },
{ "id": 719, "school": "Valley City State University" },
{ "id": 720, "school": "Universidad de Zaragoza" },
{ "id": 721, "school": "University of Engineering and Technology Lahore" },
{ "id": 722, "school": "Masaryk University" },
{ "id": 723, "school": "Australian Catholic University" },
{ "id": 724, "school": "Universidad de Jaén" },
{ "id": 725, "school": "Tenri University" },
{ "id": 726, "school": "Central University College" },
{ "id": 727, "school": "Universidad de Burgos" },
{ "id": 728, "school": "Philosophisch-Theologisches Studium Erfurt, Staatlich anerkannte Wissenschaftliche Hochschule" },
{ "id": 729, "school": "Universiti Tun Abdul Razak" },
{ "id": 730, "school": "Siberian State Industrial University" },
{ "id": 731, "school": "Universidad del Valle de Puebla" },
{ "id": 732, "school": "University of the Sciences in Philadelphia" },
{ "id": 733, "school": "Piedmont Baptist College" },
{ "id": 734, "school": "Bridgewater College" },
{ "id": 735, "school": "Willamette University" },
{ "id": 736, "school": "Universitas Krisnadwipayana" },
{ "id": 737, "school": "Universidad Central del Este" },
{ "id": 738, "school": "Beijing Institute of Technology" },
{ "id": 739, "school": "Université Chouaib Doukkali" },
{ "id": 740, "school": "Cyprus College" },
{ "id": 741, "school": "Nicola Valley Institute of Technology" },
{ "id": 742, "school": "St. Mary's College of Maryland" },
{ "id": 743, "school": "Université Jean Moulin (Lyon III)" },
{ "id": 744, "school": "Oita University" },
{ "id": 745, "school": "Isfahan University" },
{ "id": 746, "school": "Technological University (Thanlyin)" },
{ "id": 747, "school": "University of Batangas" },
{ "id": 748, "school": "Atlanta Christian College" },
{ "id": 749, "school": "Technological University (Kalay)" },
{ "id": 750, "school": "National University of Kiev-Mohyla Academy" },
{ "id": 751, "school": "Aichi Institute of Technology" },
{ "id": 752, "school": "3rd Military Medical University" },
{ "id": 753, "school": "Academy of Arts in Banská Bystrica" },
{ "id": 754, "school": "Université de La Rochelle" },
{ "id": 755, "school": "University of Manchester" },
{ "id": 756, "school": "Mississippi University for Women" },
{ "id": 757, "school": "Instituto Politécnico de Lisboa" },
{ "id": 758, "school": "Bennett College" },
{ "id": 759, "school": "Universidad Hispanoamericana" },
{ "id": 760, "school": "Australian Lutheran College" },
{ "id": 761, "school": "Tata Institute of Social Sciences" },
{ "id": 762, "school": "East-West University, Mohakhali" },
{ "id": 763, "school": "Badakhshan University" },
{ "id": 764, "school": "Kansai University of International Studies" },
{ "id": 765, "school": "Universitatea de Vest \"Vasile Goldi&#351;\" " },
{ "id": 766, "school": "Universidade Lusiada" },
{ "id": 767, "school": "Huron University" },
{ "id": 768, "school": "Yemenia University" },
{ "id": 769, "school": "Punjab Institute of Computer science" },
{ "id": 770, "school": "Dongseo University" },
{ "id": 771, "school": "Philippine Military Academy" },
{ "id": 772, "school": "St. Petersburg State University of Civil Aviation" },
{ "id": 773, "school": "Ching Kuo Institue of Management & Health" },
{ "id": 774, "school": "University of South Dakota" },
{ "id": 775, "school": "Technische Universität München" },
{ "id": 776, "school": "Université Charles-de-Gaulle (Lille III)" },
{ "id": 777, "school": "Excel College" },
{ "id": 778, "school": "Balqa Applied University" },
{ "id": 779, "school": "University Institute of Architecture Venice" },
{ "id": 780, "school": "Damghan University of Basic Sciences" },
{ "id": 781, "school": "San Jose State University" },
{ "id": 782, "school": "Universidad Autónoma del Noreste" },
{ "id": 783, "school": "Bowdoin College" },
{ "id": 784, "school": "Universidad de Hermosillo" },
{ "id": 785, "school": "University of New England, Westbrook College Campus" },
{ "id": 786, "school": "University of Zadar" },
{ "id": 787, "school": "Ulyanovsk State Pedagogical University" },
{ "id": 788, "school": "Auckland University of Technology" },
{ "id": 789, "school": "Gustav-Siewerth-Akademie" },
{ "id": 790, "school": "Mara Poly-Tech College" },
{ "id": 791, "school": "Lanzhou University" },
{ "id": 792, "school": "Universität Leipzig" },
{ "id": 793, "school": "Ho Chi Minh City University of Transport" },
{ "id": 794, "school": "Universidad Católica de Santiago de Guayaquil" },
{ "id": 795, "school": "Institut Supérieure d'Electronique de Paris" },
{ "id": 796, "school": "University of Texas Health Center at Tyler" },
{ "id": 797, "school": "West Texas A&M University" },
{ "id": 798, "school": "Medical Academy in Bialystok" },
{ "id": 799, "school": "Ecole Centrale d'Electronique - ECE" },
{ "id": 800, "school": "Mooreland University" },
{ "id": 801, "school": "Universidad Americana" },
{ "id": 802, "school": "Universidad Autónoma de San Luis Potosí" },
{ "id": 803, "school": "University of the South Pacific School of Agriculture" },
{ "id": 804, "school": "Universitas Islam Nusantara" },
{ "id": 805, "school": "Universidade Federal de Santa Maria" },
{ "id": 806, "school": "Yazd University" },
{ "id": 807, "school": "National Open University" },
{ "id": 808, "school": "University of Tromsø" },
{ "id": 809, "school": "Institute of Classical Studies, University of London" },
{ "id": 810, "school": "Sekolah Tinggi Akuntansi Negara (STAN)" },
{ "id": 811, "school": "University of Medicine and Pharmacology of Oradea" },
{ "id": 812, "school": "Open University of Sri Lanka" },
{ "id": 813, "school": "Alaska Pacific University" },
{ "id": 814, "school": "National Fisheries University" },
{ "id": 815, "school": "Charles R. Drew University of Medicine and Science" },
{ "id": 816, "school": "Estonian Academy of Security Sciences" },
{ "id": 817, "school": "University of Oulu" },
{ "id": 818, "school": "Universidad Nacional de Piura" },
{ "id": 819, "school": "Campbellsville College" },
{ "id": 820, "school": "Central Michigan University" },
{ "id": 821, "school": "Islamic Azad University, Shirvan" },
{ "id": 822, "school": "Dokkyo University" },
{ "id": 823, "school": "Brooks Institute of Photography" },
{ "id": 824, "school": "Maharishi Dayanand University, Rohtak (Haryana )" },
{ "id": 825, "school": "Near East School of Theology" },
{ "id": 826, "school": "St. Petersburg State University of Information Technologies, Mechanics and Optics" },
{ "id": 827, "school": "Kansai University of International Studies" },
{ "id": 828, "school": "Chinhoyi University of Technology" },
{ "id": 829, "school": "York College of Pennsylvania" },
{ "id": 830, "school": "University of Applied Science and Technology" },
{ "id": 831, "school": "Feng Chia University" },
{ "id": 832, "school": "Technical University of Zielona Gora" },
{ "id": 833, "school": "Christian Brothers University" },
{ "id": 834, "school": "Universidade do Algarve" },
{ "id": 835, "school": "University of Portsmouth" },
{ "id": 836, "school": "Madhya Pradesh Bhoj (Open) University" },
{ "id": 837, "school": "Ringling College of Art and Design" },
{ "id": 838, "school": "Theologische Fakultät Trier" },
{ "id": 839, "school": "International College of Tourism and Hotel Management" },
{ "id": 840, "school": "Internationale Fachhochschule Aalen" },
{ "id": 841, "school": "Zawiya Academy" },
{ "id": 842, "school": "Universidad de Ciencias y Humanidades" },
{ "id": 843, "school": "Western State University College of Law" },
{ "id": 844, "school": "Al Mamon University College" },
{ "id": 845, "school": "Obong University" },
{ "id": 846, "school": "Preston University" },
{ "id": 847, "school": "Carlow College" },
{ "id": 848, "school": "Vladimir State University" },
{ "id": 849, "school": "Trinity College Connecticut" },
{ "id": 850, "school": "Universität Bielefeld" },
{ "id": 851, "school": "Universidade Moderna de Lisboa" },
{ "id": 852, "school": "Universidad Nacional de San Agustin" },
{ "id": 853, "school": "Minamikyushu University" },
{ "id": 854, "school": "Wonkwang University" },
{ "id": 855, "school": "Silesian Technical University of Gliwice" },
{ "id": 856, "school": "Tennessee Temple University" },
{ "id": 857, "school": "Southeastern College of the Assemblies of God" },
{ "id": 858, "school": "Adekunle Ajasin University" },
{ "id": 859, "school": "University of Brunei Darussalam" },
{ "id": 860, "school": "Universidad de Managua (U de M)" },
{ "id": 861, "school": "Novosibirsk State Academy of Economics and Mangement" },
{ "id": 862, "school": "University of Limerick" },
{ "id": 863, "school": "Faculdades Integradas Toledo" },
{ "id": 864, "school": "Shiga University" },
{ "id": 865, "school": "Xiamen University" },
{ "id": 866, "school": "Mercyhurst College" },
{ "id": 867, "school": "Widener University" },
{ "id": 868, "school": "Mountain View College" },
{ "id": 869, "school": "Piedmont College" },
{ "id": 870, "school": "Universidad Maimónides" },
{ "id": 871, "school": "Fondation Universitaire Luxembourgeoise" },
{ "id": 872, "school": "Angeles University" },
{ "id": 873, "school": "Universidade de Santa Cruz do Sul" },
{ "id": 874, "school": "Dominica State College" },
{ "id": 875, "school": "University of Dodoma" },
{ "id": 876, "school": "Yangzhou University" },
{ "id": 877, "school": "Theologische Fakultät Trier" },
{ "id": 878, "school": "Concordia College, Moorhead" },
{ "id": 879, "school": "Radford University" },
{ "id": 880, "school": "Pace University" },
{ "id": 881, "school": "Richmond University - The American International University in London" },
{ "id": 882, "school": "University of Rajshahi" },
{ "id": 883, "school": "University of Applied Sciences Chur" },
{ "id": 884, "school": "Oberlin College" },
{ "id": 885, "school": "Schiller International University, London" },
{ "id": 886, "school": "Evangelische Fachhochschule für Religionspädagogik, und Gemeindediakonie Moritzburg" },
{ "id": 887, "school": "Nipissing University" },
{ "id": 888, "school": "European University Portugal" },
{ "id": 889, "school": "Shiraz University" },
{ "id": 890, "school": "Toho College of Music" },
{ "id": 891, "school": "Universitas Muhammadiyah Surakarta" },
{ "id": 892, "school": "Qufu Normal University" },
{ "id": 893, "school": "Far East State Transport University" },
{ "id": 894, "school": "University of Calabar" },
{ "id": 895, "school": "South Valley University" },
{ "id": 896, "school": "Langara College" },
{ "id": 897, "school": "Mahasarakham University" },
{ "id": 898, "school": "Glenville State College" },
{ "id": 899, "school": "Bridgewater College" },
{ "id": 900, "school": "Nortre Dame Seishin University" },
{ "id": 901, "school": "Kwararafa University" },
{ "id": 902, "school": "College for Financial Planning" },
{ "id": 903, "school": "Kagoshima Immaculate Heart University" },
{ "id": 904, "school": "Maldives National University" },
{ "id": 905, "school": "Mountain State University" },
{ "id": 906, "school": "Iact College" },
{ "id": 907, "school": "John Brown University" },
{ "id": 908, "school": "Universidad de La Salle" },
{ "id": 909, "school": "Fundación Universitaria San Martín" },
{ "id": 910, "school": "University of North America" },
{ "id": 911, "school": "Institut Supérieur de Commerce et d'Administration des Entreprises" },
{ "id": 912, "school": "Hiroshima Shudo University" },
{ "id": 913, "school": "Open University" },
{ "id": 914, "school": "Universidad Metropolitana" },
{ "id": 915, "school": "Cheljabinsk State Institute of Teacher Training" },
{ "id": 916, "school": "Tshwane University of Technology" },
{ "id": 917, "school": "Korea University" },
{ "id": 918, "school": "Norton University" },
{ "id": 919, "school": "Fernuniversität Gesamthochschule Hagen" },
{ "id": 920, "school": "King's College" },
{ "id": 921, "school": "Fachhochschule für Bank- und Finanzwirtschaft" },
{ "id": 922, "school": "City University of New York, Brooklyn College" },
{ "id": 923, "school": "American University College of Technology" },
{ "id": 924, "school": "St. Louis College of Pharmacy" },
{ "id": 925, "school": "Dammam Community College" },
{ "id": 926, "school": "Université du Québec en Outaouais" },
{ "id": 927, "school": "Fatih University" },
{ "id": 928, "school": "Université de la Méditerranée (Aix Marseille II)" },
{ "id": 929, "school": "Keuka College" },
{ "id": 930, "school": "Yasuda Women's University" },
{ "id": 931, "school": "Corporación Educativa Mayor del Desarrollo \"Simón Bolivar\"" },
{ "id": 932, "school": "Institute of Teachers Education, Dato' Razali Ismail " },
{ "id": 933, "school": "Universidade Católica de Santos" },
{ "id": 934, "school": "Wheaton College Massachusetts" },
{ "id": 935, "school": "Thierry Graduate School of Leadership" },
{ "id": 936, "school": "Umea University" },
{ "id": 937, "school": "Université des Sciences Sociales (Toulouse I)" },
{ "id": 938, "school": "Université Denis Diderot (Paris VII)" },
{ "id": 939, "school": "DeSales University" },
{ "id": 940, "school": "Ecole Nationale Supérieure d'Electronique, d'Electrotechnique, d'Informatique et d'Hydraulique de Toulouse" },
{ "id": 941, "school": "Oklahoma State University - Institute of Technology" },
{ "id": 942, "school": "University of Dongola" },
{ "id": 943, "school": "Universidad Adventista de Colombia" },
{ "id": 944, "school": "Albany Law School" },
{ "id": 945, "school": "Chongqing Normal University Foreign Trade and Business College" },
{ "id": 946, "school": "Bugema University" },
{ "id": 947, "school": "University of Science and Technology" },
{ "id": 948, "school": "Philadelphia University" },
{ "id": 949, "school": "Institut Catholique de Paris" },
{ "id": 950, "school": "Hope College" },
{ "id": 951, "school": "Samara State Medical University" },
{ "id": 952, "school": "Olivet College" },
{ "id": 953, "school": "Universidad Insurgentes Plantel León" },
{ "id": 954, "school": "Universidad Tecnológica del Choco \"Diego Luis Cordoba\"" },
{ "id": 955, "school": "Universidade Metodista de Angola" },
{ "id": 956, "school": "Universidade Nova de Lisboa" },
{ "id": 957, "school": "Sekolah Tinggi Akuntansi Negara (STAN)" },
{ "id": 958, "school": "Mozyr State Pedagogical Institute" },
{ "id": 959, "school": "Xi'an Jiaotong University" },
{ "id": 960, "school": "University of Texas at Austin" },
{ "id": 961, "school": "Western State University College of Law - Orange County" },
{ "id": 962, "school": "Islamic Azad University, Sanandaj" },
{ "id": 963, "school": "University of King's College" },
{ "id": 964, "school": "Southern Oregon University" },
{ "id": 965, "school": "Fachhochschule für die Wirtschaft" },
{ "id": 966, "school": "Nippon Bunri University" },
{ "id": 967, "school": "Ming Chuan University" },
{ "id": 968, "school": "Lawrence University" },
{ "id": 969, "school": "Fisk University" },
{ "id": 970, "school": "Tbilisi State Medical University" },
{ "id": 971, "school": "Nara University of Education" },
{ "id": 972, "school": "Suez Canal University" },
{ "id": 973, "school": "Technological Education Institute of Heraklion" },
{ "id": 974, "school": "Integral University" },
{ "id": 975, "school": "Mbarara University of Science and Technology" },
{ "id": 976, "school": "Technical University of Zielona Gora" },
{ "id": 977, "school": "New College of Florida" },
{ "id": 978, "school": "University of Kashmir" },
{ "id": 979, "school": "UCSI University" },
{ "id": 980, "school": "Shahrekord University of Medical Sciences" },
{ "id": 981, "school": "Universidad Internacional SEK, Quito" },
{ "id": 982, "school": "College of Europe" },
{ "id": 983, "school": "Touro University" },
{ "id": 984, "school": "Azerbaijan Diplomatic Academy" },
{ "id": 985, "school": "University of Seychelles - American Institute of Medicine" },
{ "id": 986, "school": "Lucerne University of Applied Sciences and Arts " },
{ "id": 987, "school": "Gulf University College" },
{ "id": 988, "school": "Sungshin Women's University" },
{ "id": 989, "school": "State University of New York College at Oneonta" },
{ "id": 990, "school": "Universidade Portucalense Infante D. Henrique" },
{ "id": 991, "school": "Kakatiya University" },
{ "id": 992, "school": "Royal School of Library and Information Science" },
{ "id": 993, "school": "Tamagawa University" },
{ "id": 994, "school": "University of Bacau" },
{ "id": 995, "school": "University of Calcutta" },
{ "id": 996, "school": "Dutch University Institute for Art History (DUIA)" },
{ "id": 997, "school": "Webster University Geneva" },
{ "id": 998, "school": "University of the Punjab" },
{ "id": 999, "school": "American University of Afghanistan" },
{ "id": 1000, "school": "Telugu University" }]